// =================================================================================
// This is auto-generated by Suxin CLI tool only once. Fill this file as you wish.
// =================================================================================

package dict

import (
	"github.com/suxinwl/GoSuxin/framework/cmd/suxin/internal/cmd/testdata/genctrl/merge/add_new_ctrl/api/dict"
)

type ControllerV1 struct{}

func NewV1() dict.IDictV1 {
	return &ControllerV1{}
}
