package suxinvideo

import (
	"html/template"
	"strings"
)

// Guoguo uses the source project's component classes and stylesheet while
// keeping the CMS catalogue, account and playback routes.
const guoguoPage = `<!doctype html><html lang="zh-CN" class="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#12171b"><title>{{.Title}} - {{.SiteName}}</title><meta name="description" content="{{.SiteDescription}}"><meta name="keywords" content="{{.SiteKeywords}}"><link rel="icon" href="{{.SiteFavicon}}"><link rel="apple-touch-icon" href="{{.SiteLogo}}"><link rel="stylesheet" href="/suxinvideo/asset?theme=guoguo&file=main.css&v=2.3.29"></head>
<body class="sx-theme-guoguo theme-4kvm" data-page="{{if .PageKind}}{{.PageKind}}{{else}}library{{end}}"><a class="skip-link" href="#workspaceMain">跳到主要内容</a>
<header class="navbar-4kvm"><div class="navbar-inner"><div><a class="navbar-logo brand" href="/suxinvideo/" aria-label="首页">{{if .SiteLogo}}<img class="sx-brand-logo" src="{{.SiteLogo}}" alt="">{{else}}<span class="guoguo-brand-mark">▶</span>{{end}}<span class="sx-brand-name">{{.SiteName}}</span></a><nav class="nav-links-desktop" aria-label="主菜单"><a class="nav-item-4kvm" href="/suxinvideo/live">直播</a><a class="nav-item-4kvm" href="/suxinvideo/">首页</a>{{range .NavTypes}}<a class="nav-item-4kvm nav-category" href="{{navURL .}}">{{.name}}</a>{{end}}<a class="nav-item-4kvm" href="/suxinvideo/app-download">APP下载</a><a class="nav-item-4kvm" href="/suxinvideo/favorites">片单</a></nav></div>
<div class="navbar-actions"><form class="nav-search-form" action="/suxinvideo/search" role="search"><input class="nav-search-input" type="search" name="wd" placeholder="输入片名进行搜索" maxlength="80" required><button class="nav-search-btn" type="submit" aria-label="搜索">⌕</button></form><div id="navHistoryWrap" class="relative"><button class="nav-icon-btn" id="navHistoryBtn" type="button" title="观看历史" aria-label="观看历史" aria-expanded="false">◷</button><div class="history-popover" id="navHistoryPopover"><div class="history-popover-header"><h3>观看历史</h3><button id="navHistoryClearBtn" type="button">清空</button></div><div class="history-popover-body" id="navHistoryList"></div><a class="secondary" href="/suxinvideo/history">查看全部记录</a></div><div class="history-mobile-panel" id="navHistoryMobile"><div class="history-popover-header"><h3>观看历史</h3><button id="navHistoryMobileClearBtn" type="button">清空</button><button class="quiet" type="button" data-history-close>关闭</button></div><div id="navHistoryMobileList"></div><a class="secondary" href="/suxinvideo/history">查看全部记录</a></div></div><button class="nav-icon-btn" type="button" data-theme-toggle aria-label="切换明暗主题">☾</button><a class="nav-icon-btn" id="openAccountBtn" href="/suxinvideo/center"><span id="accountLabel">{{if .Logged}}我的账号{{else}}注册 | 登录{{end}}</span></a><button class="nav-mobile-toggle" id="mobileMenuToggle" type="button" aria-label="打开菜单" aria-expanded="false" aria-controls="sx-mobile-navigation">☰</button></div></div>
<nav class="mobile-menu-drawer" id="sx-mobile-navigation" aria-label="移动端菜单"><div class="mobile-menu-search"><form action="/suxinvideo/search"><input class="nav-search-input" type="search" name="wd" placeholder="输入片名进行搜索" required><button class="nav-search-btn" aria-label="搜索">⌕</button></form></div><div class="mobile-menu-links"><a class="nav-item-4kvm" href="/suxinvideo/live">直播</a><a class="nav-item-4kvm" href="/suxinvideo/">首页</a>{{range .NavTypes}}<a class="nav-item-4kvm nav-category" href="{{navURL .}}">{{.name}}</a>{{end}}<a class="nav-item-4kvm" href="/suxinvideo/app-download">APP下载</a><a class="nav-item-4kvm" href="/suxinvideo/favorites">我的片单</a><a class="nav-item-4kvm" href="/suxinvideo/history">观看历史</a><a class="nav-item-4kvm" href="/suxinvideo/center">我的账号</a></div></nav></header>
<main class="workspace cms-body{{if .FullWidth}} sx-guoguo-home{{else}} sx-guoguo-content{{end}}" id="workspaceMain"><div class="page-view">{{.Body}}</div></main><footer class="guoguo-footer"><a href="/suxinvideo/articles">文章公告</a> · <a href="/suxinvideo/sitemap">站点地图</a> · <a href="/suxinvideo/rss">RSS</a> · {{.SiteName}} {{.SiteICP}}</footer><div class="toast" id="messageText" role="status" aria-live="polite"></div><script src="/suxinvideo/asset?theme=guoguo&file=main.js&v=2.3.29" defer></script></body></html>`

const guoguoCards = `{{define "cards"}}<div class="replica-card-grid">{{range .}}{{template "guoguoCard" .}}{{else}}<p class="empty">暂无影片</p>{{end}}</div>{{end}}` + guoguoCard

const guoguoCard = `{{define "guoguoCard"}}<article class="card"><div class="movie-card-default"><a class="poster" href="{{vodURL .}}" aria-label="观看 {{.name}}"><div class="movie-poster"><img class="cover" src="{{pic .pic}}" alt="{{.name}}" loading="lazy" decoding="async" onerror="this.onerror=null;this.src='/suxinvideo/asset?theme=guoguo&file=nopic.svg'">{{if eq (str .vip) "1"}}<span class="badge-4k">VIP</span>{{end}}<span class="episode-badge">{{.remarks}}</span></div></a><h3 class="movie-card-title"><a href="{{vodURL .}}">{{.name}}</a></h3></div><div class="movie-card-preview"><a class="preview-cover" href="{{vodURL .}}"><img src="{{pic .pic}}" alt="" loading="lazy" onerror="this.onerror=null;this.src='/suxinvideo/asset?theme=guoguo&file=nopic.svg'"><span class="preview-play-btn-wrap"><span class="preview-play-btn">▶</span></span></a><div class="preview-info"><a class="preview-title" href="{{vodURL .}}">{{.name}}</a><div class="preview-meta"><span>{{.year}}</span><span>{{.area}}</span>{{if scoreAvailable .}}<span class="score" title="{{scoreSource .}}">{{scoreLabel .}}</span>{{end}}</div><p class="preview-desc">{{.remarks}}</p><div class="preview-actions"><a class="preview-action-btn" href="{{vodURL .}}" aria-label="观看影片">▶</a>{{if .id}}<button class="preview-action-btn" type="button" data-follow-id="{{.id}}" aria-label="收藏影片">☆</button>{{end}}</div></div></div></article>{{end}}`

const guoguoHomeBody = `<div id="heroBanner4kvm">{{if .Hero}}<section class="reference-hero" aria-label="精选影视" aria-roledescription="轮播"><div class="reference-hero__viewport"><div class="reference-hero__track">{{range $i,$hero:=.Hero}}<article class="reference-hero__slide{{if eq $i 0}} is-active{{end}}" aria-roledescription="幻灯片"><a class="reference-hero__link" href="{{$hero.Link}}"><img class="reference-hero__image" src="{{pic $hero.Pic}}" alt="{{$hero.Name}}" decoding="async" draggable="false"><div class="reference-hero__shade"></div><span class="guoguo-hero-image-notice" role="status">图片暂不可用，已显示备用背景</span><div class="reference-hero__content"><h2 class="reference-hero__title">{{$hero.Name}}</h2><p class="reference-hero__description">{{$hero.Description}}</p><p class="reference-hero__meta">{{$hero.Year}} {{$hero.Category}} {{$hero.Remarks}}</p>{{if not $hero.Film}}<span class="guoguo-hero-detail">查看详情 ›</span>{{end}}</div></a></article>{{end}}</div></div><button class="reference-hero__arrow reference-hero__arrow--previous" type="button" aria-label="上一张">‹</button><button class="reference-hero__arrow reference-hero__arrow--next" type="button" aria-label="下一张">›</button><div class="reference-hero__pagination">{{range $i,$hero:=.Hero}}<button class="reference-hero__dot{{if eq $i 0}} is-active{{end}}" type="button" data-index="{{$i}}" aria-label="精选 {{$hero.Name}}"></button>{{end}}</div></section>{{end}}</div>
<div class="category-tabs"><nav class="category-tabs-inner"><div><a class="tab-pill active" href="/suxinvideo/">首页</a><a class="tab-pill" href="{{.RecentMoreURL}}">最近更新</a><a class="tab-pill" href="{{.HotMoreURL}}">热播</a><a class="tab-pill" href="/suxinvideo/channel?id=0">全部影片</a></div></nav></div>
<div id="replicaCatalog"><div class="replica-home-top"><section class="replica-section replica-section-newest"><div class="replica-section-heading"><h2>最近更新</h2><a class="replica-section-link" href="{{.RecentMoreURL}}">查看全部 ›</a></div>{{if .GuoguoRecent}}{{template "cards" .GuoguoRecent}}{{else}}{{template "cards" .Recent}}{{end}}</section><aside id="sidebarRankings4kvm"><div class="rankings-sidebar"><h2>热门排行榜</h2>{{range $i,$v:=.GuoguoRanking}}<a class="ranking-item" href="{{vodURL $v}}"><span class="ranking-index">{{$v.rank}}</span><div class="ranking-cover"><img src="{{pic $v.pic}}" alt="" loading="lazy" onerror="this.onerror=null;this.src='/suxinvideo/asset?theme=guoguo&file=nopic.svg'"></div><div class="ranking-info"><strong>{{$v.name}}</strong><span>{{$v.remarks}}</span></div></a>{{else}}<p class="small">暂无排行</p>{{end}}</div></aside></div>
<section class="replica-section replica-section-weekly"><div class="replica-section-heading"><h2>热播</h2><a class="replica-section-link" href="{{.HotMoreURL}}">查看全部 ›</a></div><div class="replica-card-grid">{{range $i,$v:=.Hot}}<div class="card guoguo-ranked-card"><span class="replica-rank">{{$v.rank}}</span>{{template "guoguoCard" $v}}</div>{{else}}<p class="empty">暂无影片</p>{{end}}</div></section>
{{range .HomeBlocks}}<section class="replica-section"><div class="replica-section-heading"><h2>{{.Name}}</h2><a class="replica-section-link" href="{{if .MoreURL}}{{.MoreURL}}{{else}}/suxinvideo/type?id={{.ID}}{{end}}">查看全部 ›</a></div>{{template "cards" .Vods}}</section>{{end}}{{if .Links}}<section class="replica-section"><div class="replica-section-heading"><h2>友情链接</h2></div><div class="sx-links">{{range .Links}}<a href="{{.url}}" target="_blank" rel="noopener noreferrer">{{.name}}</a>{{end}}</div></section>{{end}}</div>` + guoguoHeroScript

const guoguoHeroScript = `<script>(function(){const root=document.querySelector('.reference-hero');if(!root)return;const viewport=root.querySelector('.reference-hero__viewport'),track=root.querySelector('.reference-hero__track'),original=[...track.children],dots=[...root.querySelectorAll('.reference-hero__dot')],previous=root.querySelector('.reference-hero__arrow--previous'),next=root.querySelector('.reference-hero__arrow--next');let index=0,physical=original.length>1?1:0,timer=0,normalizer=0,drag=null;const reduce=matchMedia('(prefers-reduced-motion: reduce)');
if(original.length>1){track.prepend(original.at(-1).cloneNode(true));track.append(original[0].cloneNode(true))}else{previous.hidden=next.hidden=true;root.querySelector('.reference-hero__pagination').hidden=true}
function position(animate){const slide=track.children[physical];if(!slide)return;track.style.transitionDuration=animate&&!reduce.matches?'500ms':'0ms';track.style.transform='translate3d('+(viewport.clientWidth/2-slide.offsetLeft-slide.offsetWidth/2)+'px,0,0)';[...track.children].forEach((s,i)=>{s.classList.toggle('is-active',i===physical);s.setAttribute('aria-hidden',String(i!==physical));s.querySelector('a').tabIndex=i===physical?0:-1});dots.forEach((d,i)=>{d.classList.toggle('is-active',i===index);d.setAttribute('aria-pressed',String(i===index))})}
function stop(){clearTimeout(timer)}function schedule(){stop();if(original.length>1&&!document.hidden&&!reduce.matches)timer=setTimeout(()=>move(1),15000)}function show(i,direction=0){clearTimeout(normalizer);const before=index;index=(i+original.length)%original.length;physical=original.length>1?index+1:0;if(direction>0&&before===original.length-1&&index===0)physical=original.length+1;if(direction<0&&before===0&&index===original.length-1)physical=0;position(true);normalizer=setTimeout(()=>{physical=original.length>1?index+1:0;position(false)},520);schedule()}function move(n){show(index+n,n)}previous.onclick=()=>move(-1);next.onclick=()=>move(1);dots.forEach((dot,i)=>dot.onclick=()=>show(i));root.onpointerenter=stop;root.onpointerleave=schedule;root.onfocusin=stop;root.onfocusout=schedule;root.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1)}});root.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;drag={x:e.clientX,y:e.clientY};stop()});root.addEventListener('pointerup',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag=null;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)){e.preventDefault();move(dx<0?1:-1);const block=event=>{event.preventDefault();event.stopPropagation()};root.addEventListener('click',block,{capture:true,once:true});setTimeout(()=>root.removeEventListener('click',block,true),300)}else schedule()});root.addEventListener('pointercancel',()=>{drag=null;schedule()});root.querySelectorAll('img').forEach(img=>{const failed=()=>img.closest('.reference-hero__slide').classList.add('image-unavailable');img.addEventListener('error',failed,{once:true});if(img.complete&&!img.naturalWidth)failed()});addEventListener('resize',()=>position(false));if(window.ResizeObserver)new ResizeObserver(()=>position(false)).observe(viewport);document.addEventListener('visibilitychange',schedule);addEventListener('pagehide',()=>{stop();clearTimeout(normalizer)});position(false);schedule()})();</script>`

func init() {
	themePages["guoguo"] = template.Must(template.New("page").Funcs(themeFunctions).Parse(guoguoPage + guoguoCards))
}

func guoguoBody(body string) string {
	if body != playThemeBody {
		return body
	}
	body = strings.Replace(body, `<div class="play-wrap">`, `<div class="play-wrap play-page">`, 1)
	body = strings.Replace(body, `<div><div class="player-box"`, `<div id="playerPanel"><div class="player-box"`, 1)
	body = strings.Replace(body, `<aside class="pinfo">`, `<aside class="pinfo play-reference-sidebar" id="playSidebar">`, 1)
	body = strings.Replace(body, `<div class="pacts">`, `<div class="pacts play-reference-actions">`, 1)
	body = strings.Replace(body, `<button type="button" id="shareVod">🔗 影片分享</button></div>`, `<button type="button" id="shareVod">🔗 影片分享</button><a href="/suxinvideo/favorites">我的片单</a><a href="#comments">影片评论</a></div><div class="play-membership"><strong>VIP 会员，畅享更多好片</strong><div><span>会员影片</span><span>积分解锁</span><span>多端观看</span></div><a class="btn-main" href="/suxinvideo/pay">开通或续费 VIP</a></div>`, 1)
	body = strings.Replace(body, `<div class="ep-grid" id="epGrid"></div>`, `<form id="guoguoEpisodeJump" class="episode-jump"><label>跳转分集 <input name="episode" type="number" min="1" inputmode="numeric" placeholder="集数" required></label><button type="submit">跳转</button><span role="status"></span></form><div class="ep-grid play-reference-episodes" id="epGrid"></div>`, 1)
	return body
}

// Copy ranking fields so cached provider results and other themes stay intact.
func guoguoRanked(items []row, limit int) []row {
	if len(items) > limit {
		items = items[:limit]
	}
	result := copyHomeVods(items)
	for i := range result {
		result[i]["rank"] = i + 1
	}
	return result
}
