// =================================================================================
// This is auto-generated by Suxin CLI tool only once. Fill this file as you wish.
// =================================================================================

package hello

import (
	"github.com/suxinwl/GoSuxin/framework/cmd/suxin/internal/cmd/testdata/issue/3460/api/hello"
)

type ControllerV1 struct{}

func NewV1() hello.IHelloV1 {
	return &ControllerV1{}
}

type ControllerV2 struct{}

func NewV2() hello.IHelloV2 {
	return &ControllerV2{}
}
