import type { RouteRecordNormalized } from 'vue-router';
import type { AppRouteRecordRaw } from '/@/router/types';
export type LayoutMode = 'left' | 'top' | 'columns';
export type TabMode = 'googlecard' | 'card' | 'card-gutter' | 'rounded';
export interface AppState {
  theme: string;
  layout: LayoutMode;
  colorWeak: boolean;
  navbar: boolean;
  menu: boolean;
  topMenu: boolean;
  hideMenu: boolean;
  menuCollapse: boolean;
  footer: boolean;
  breadcrumb: boolean;
  breadcrumbHeight: number;
  themeColor: string;
  menuDark: boolean;
  navBg: boolean;
  menuWidth: number;
  globalSettings: boolean;
  device: string;
  tabBar: boolean;
  tabMode: TabMode;
  menuFromServer: boolean;
  menuAccordion: boolean;
  serverMenu: RouteRecordNormalized[];
  serverRoute: AppRouteRecordRaw[];
  isDynamicAddedRoute:boolean;
  [key: string]: unknown;
}
