#应用信息
app:
     #版本号
     version: 1.0.0
     #名称
     title: 
     #描述
     des: 
     #标识包目录名
     name: 
     #安装状态
     isinstall: false
     #安装是否为覆盖原来代码
     installcover: false
     #mod拉取依赖
     isModTidy: false
     #Vue前端依赖命令行
     commandLines: 
     #Go后端文件路径
     goFiles: 
     #vue前端文件路径
     vueFiles: 
     #安装后模块
     modellist: 
sqldb:
     #数据库表名称（多个,分开）
     packtables: 
     #菜单ID，安装后返回的ID
     adminmenuids: 
