<template><div class="card"><div class="searchbar"><span>共 <b>{{ total }}</b> 张本地化影片图片</span><span>占用 <b>{{ (size/1048576).toFixed(1) }} MB</b></span><span style="color:var(--red)">未引用 <b>{{ orphan }}</b> 张</span><button v-if="actions['images/clean']" class="btn sm" @click="cleanOrphans">清理全部未引用图片</button><button v-if="actions['images/delete']" class="btn sm" @click="removeSelected">删除选中</button></div><p class="hint">未引用图片指不被影片封面或幻灯使用的本地文件。</p><div class="tb-wrap"><table class="tb"><thead><tr><th><input type="checkbox" @change="selectAll" /></th><th>预览</th><th>文件名</th><th>大小</th><th>时间</th><th>引用状态</th></tr></thead><tbody><tr v-for="item in files" :key="item.name"><td><input v-model="selected" type="checkbox" :value="item.name" /></td><td><img :src="item.url" style="height:38px;border-radius:5px" alt="封面" /></td><td><code>{{ item.name }}</code></td><td>{{ (item.size/1024).toFixed(1) }} KB</td><td>{{ new Date(item.time*1000).toLocaleString('zh-CN') }}</td><td><span class="tag" :class="item.used?'g':'r'">{{ item.used?'使用中':'未引用' }}</span></td></tr><tr v-if="!files.length"><td colspan="6" class="hint">暂无本地化图片</td></tr></tbody></table></div><div class="sx-page"><select v-model="perPage" @change="page=1;load()"><option v-for="n in [50,100,200,500,1000]" :key="n" :value="n">{{ n }} 张/页</option></select><button :disabled="page<=1" @click="page--;load()">上一页</button><button class="cur">第 {{ page }} / {{ Math.max(1,Math.ceil(total/perPage)) }} 页</button><button :disabled="page*perPage>=total" @click="page++;load()">下一页</button></div></div></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue';import { Message, Modal } from '@arco-design/web-vue';import { defHttp } from '@/utils/http';
defineProps<{actions:Record<string,boolean>}>();
const files=ref<Record<string,any>[]>([]);const selected=ref<string[]>([]);const total=ref(0);const size=ref(0);const orphan=ref(0);const page=ref(1);const perPage=ref(50);
async function load(){const result=await defHttp.get({url:'/suxinvideo/images',params:{page:page.value,per_page:perPage.value}});files.value=result.list||[];total.value=result.total||0;size.value=result.size||0;orphan.value=result.orphan||0;selected.value=[];}
function selectAll(event:Event){selected.value=(event.target as HTMLInputElement).checked?files.value.map(item=>item.name):[];}
function removeSelected(){if(!selected.value.length){Message.warning('请先勾选图片');return;}Modal.confirm({title:`删除选中的 ${selected.value.length} 张图片？`,content:'删除的图片无法恢复。',onOk:async()=>{await defHttp.post({url:'/suxinvideo/images/delete',params:{names:selected.value}});await load();}});}
function cleanOrphans(){Modal.confirm({title:'清理全部未引用图片？',content:'将删除未被内容引用的图片文件。',onOk:async()=>{await defHttp.post({url:'/suxinvideo/images/clean',params:{}});await load();}});}
onMounted(load);
</script>
