<template>
  <section class="card live-admin">
    <div class="live-admin-head"><div><h2>直播管理</h2><p class="hint">同频道合并多条线路；订阅每六小时刷新，失败保留原有数据。新线路先检测，不可用线路保留状态。</p></div><a class="btn plain" href="/suxinvideo/live" target="_blank" rel="noopener">直播预览 ↗</a></div>
    <div class="tabs"><button v-for="item in visibleTabs" :key="item.key" :class="{on:tab===item.key}" @click="setTab(item.key)">{{item.name}}</button></div>
    <p v-if="error" class="live-admin-error" role="alert">{{error}}</p>
    <div v-if="job" class="live-job" role="status" aria-live="polite"><b>{{jobLabel(job.status)}}</b><span>{{job.message || '正在导入或检测直播源'}}</span><progress :max="Math.max(1,job.total || 1)" :value="job.processed || 0" /><small>进度 {{job.processed || 0}} / {{job.total || 0}} · 新增 {{job.added || 0}} · 更新 {{job.updated || 0}} · 失败 {{job.failed || 0}}</small><button v-if="!isActiveJob" class="btn plain sm" @click="job=null">收起</button></div>

    <template v-if="tab==='channels'">
      <form class="searchbar" @submit.prevent="page=1;loadChannels()"><input v-model="query" type="text" placeholder="频道名或 tvg-id" /><select v-model.number="groupFilter" @change="page=1;loadChannels()"><option :value="0">全部分组</option><option v-for="item in groups" :key="item.id" :value="item.id">{{item.name}}</option></select><button class="btn plain" :disabled="loading">查询</button><button v-if="can('save')" type="button" class="btn" @click="edit('channel')">添加频道</button><button v-if="can('import')" type="button" class="btn blue" @click="openImport">导入 M3U / TXT</button></form>
      <div class="tb-wrap"><table class="tb"><thead><tr><th>频道</th><th>分组 / tvg-id</th><th>排序</th><th>可用线路</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in channels" :key="item.id"><td><div class="live-channel-name"><img v-if="item.logo" :src="item.logo" alt="" @error="($event.target as HTMLImageElement).style.display='none'" /><b>{{item.name}}</b></div></td><td>{{item.group_name || '未分组'}}<br><small class="hint">{{item.tvg_id || '按名称匹配'}}</small></td><td>{{item.sort || 0}}</td><td>{{item.healthy_count || 0}} / {{item.stream_count || 0}}</td><td><span class="tag" :class="item.enabled ? 'g':'gr'">{{item.enabled ? '启用':'停用'}}</span><small v-if="item.manual_edited" class="hint"> 手动配置</small></td><td class="live-table-ops"><a class="btn plain sm" :href="'/suxinvideo/live?channel='+item.id" target="_blank" rel="noopener">预览</a><button v-if="can('streams')" class="btn plain sm" @click="showStreams(item)">线路</button><button v-if="can('save')" class="btn plain sm" @click="edit('channel',item)">编辑</button><button v-if="can('delete')" class="btn plain sm" @click="remove('channel',item)">停用</button></td></tr><tr v-if="!channels.length"><td colspan="6" class="hint">{{loading?'正在加载…':'暂无频道，请添加订阅或导入直播清单。'}}</td></tr></tbody></table></div>
      <nav class="live-pagination"><button class="btn plain sm" :disabled="page<=1 || loading" @click="page--;loadChannels()">上一页</button><span>{{page}} / {{Math.max(1,Math.ceil(total/size))}} · 共 {{total}} 个频道</span><button class="btn plain sm" :disabled="page*size>=total || loading" @click="page++;loadChannels()">下一页</button></nav>
    </template>
    <template v-else-if="tab==='groups'">
      <div class="searchbar"><button v-if="can('save')" class="btn" @click="edit('group')">添加分组</button><button class="btn plain" @click="loadGroups">刷新列表</button></div>
      <div class="tb-wrap"><table class="tb"><thead><tr><th>名称</th><th>排序</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in groups" :key="item.id"><td>{{item.name}}</td><td>{{item.sort || 0}}</td><td><span class="tag" :class="item.enabled ? 'g':'gr'">{{item.enabled?'启用':'停用'}}</span></td><td class="live-table-ops"><button v-if="can('save')" class="btn plain sm" @click="edit('group',item)">编辑</button><button v-if="can('delete')" class="btn plain sm" @click="remove('group',item)">停用</button></td></tr><tr v-if="!groups.length"><td colspan="4" class="hint">暂无分组</td></tr></tbody></table></div>
    </template>
    <template v-else-if="tab==='streams'">
      <div class="searchbar"><b>{{selectedChannel?.name || '请先在频道列表选择一个频道'}}</b><button class="btn plain" @click="setTab('channels')">返回频道</button><button v-if="selectedChannel && can('save')" class="btn" @click="edit('stream')">添加线路</button><button v-if="selectedChannel" class="btn plain" @click="loadStreams">刷新状态</button></div>
      <p class="hint">优先级数值越大越优先；健康线路优先播放。检测不通过不会删除线路。源地址与请求头仅在管理后台显示。</p>
      <div class="tb-wrap"><table class="tb"><thead><tr><th>线路 / 地址</th><th>优先级</th><th>清晰度</th><th>健康状态</th><th>启停</th><th>操作</th></tr></thead><tbody><tr v-for="item in streams" :key="item.id"><td><b>{{item.name || '线路 '+item.id}}</b><div class="live-stream-url" :title="item.url">{{item.url}}</div></td><td>{{item.priority || 0}}</td><td>{{item.quality || '检测后显示'}}</td><td><span class="tag" :class="item.health==='healthy'?'g':['unhealthy','unavailable'].includes(item.health)?'r':'gr'">{{healthLabel(item.health)}}</span><div v-if="item.last_error" class="live-small-error">{{item.last_error}}</div><small class="hint">{{dateLabel(item.last_checked)}}</small></td><td>{{item.enabled?'启用':'停用'}}</td><td class="live-table-ops"><button v-if="can('probe')" class="btn plain sm" :disabled="probing===item.id" @click="probe(item)">{{probing===item.id?'检测中…':'检测'}}</button><button v-if="can('save')" class="btn plain sm" @click="edit('stream',item)">编辑</button><button v-if="can('delete')" class="btn plain sm" @click="remove('stream',item)">停用</button></td></tr><tr v-if="!streams.length"><td colspan="6" class="hint">{{selectedChannel?'此频道尚无线路':'选择频道后可管理线路'}}</td></tr></tbody></table></div>
    </template>
    <LiveProvider v-else-if="tab==='provider'" :actions="actions" />
    <template v-else>
      <div class="searchbar"><button v-if="can('save')" class="btn" @click="edit('subscription')">添加订阅</button><button v-if="can('refresh')" class="btn blue" :disabled="busy || isActiveJob" @click="refresh(0)">立即刷新全部订阅</button><button v-if="can('import')" class="btn plain" @click="openImport">一次性导入</button></div>
      <div class="tb-wrap"><table class="tb"><thead><tr><th>名称 / URL</th><th>刷新周期</th><th>上次刷新</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in subscriptions" :key="item.id"><td><b>{{item.name}}</b><div class="live-stream-url" :title="item.url">{{item.url}}</div></td><td>{{item.interval_hours || 6}} 小时</td><td>{{dateLabel(item.last_refresh)}}<div v-if="item.last_error" class="live-small-error">{{item.last_error}}</div></td><td><span class="tag" :class="item.enabled?'g':'gr'">{{item.enabled?'启用':'停用'}}</span></td><td class="live-table-ops"><button v-if="can('refresh')" class="btn plain sm" :disabled="busy || isActiveJob" @click="refresh(item.id)">刷新</button><button v-if="can('save')" class="btn plain sm" @click="edit('subscription',item)">编辑</button><button v-if="can('delete')" class="btn plain sm" @click="remove('subscription',item)">停用</button></td></tr><tr v-if="!subscriptions.length"><td colspan="5" class="hint">暂无订阅</td></tr></tbody></table></div>
    </template>
  </section>

  <div v-if="editing" class="modal" @click.self="editing=null"><form class="mbox live-editor" @submit.prevent="save"><h3>{{editing.id?'编辑':'添加'}}{{kindLabel(editing.kind)}}</h3>
    <div class="fi"><label>名称</label><input v-model="editing.data.name" type="text" maxlength="200" required /></div>
    <template v-if="editing.kind==='channel'"><div class="row"><div class="fi"><label>分组</label><select v-model.number="editing.data.group_id"><option :value="0" disabled>请选择分组</option><option v-for="item in groups" :key="item.id" :value="item.id">{{item.name}}</option></select></div><div class="fi"><label>tvg-id</label><input v-model="editing.data.tvg_id" type="text" maxlength="200" /></div></div><div class="fi"><label>频道图标 URL</label><input v-model="editing.data.logo" type="text" placeholder="https://…" /></div><div class="fi"><label>别名（每行一个）</label><textarea v-model="aliasesText" rows="3" placeholder="例如：TVB翡翠台、Jade" /><p class="hint">缺少 tvg-id 的清单可按名称和别名合并，避免把不同频道合并。翡翠台与黄金翡翠台分别管理。</p></div></template>
    <template v-if="editing.kind==='stream' || editing.kind==='subscription'"><div class="fi"><label>{{editing.kind==='stream'?'HLS 地址':'M3U / TXT 订阅 URL'}}</label><input v-model="editing.data.url" type="text" placeholder="https://…" required /></div></template>
    <template v-if="editing.kind==='stream'"><div class="fi"><label>请求头 JSON（可选）</label><textarea v-model="headersText" rows="3" placeholder='{"Referer":"https://example.com/"}' /><p class="hint">密钥类请求头脱敏显示。留空时保留已有请求头，不把脱敏值提交为新密钥。</p></div><div class="fi"><label>优先级（越大越优先）</label><input v-model.number="editing.data.priority" type="number" min="0" max="10000" /></div></template>
    <div v-if="editing.kind==='group' || editing.kind==='channel'" class="fi"><label>排序（越小越靠前）</label><input v-model.number="editing.data.sort" type="number" /></div>
    <p v-if="editing.kind==='subscription'" class="hint">订阅固定每六小时自动刷新；导入结果按频道合并，不覆盖手动名称、排序或启停设置。</p>
    <div class="fi"><label><input v-model="editing.data.enabled" type="checkbox" /> 启用</label></div><p v-if="formError" class="live-admin-error" role="alert">{{formError}}</p><div class="form-actions"><button class="btn" :disabled="busy">{{busy?'保存中…':'保存'}}</button><button type="button" class="btn plain" @click="editing=null">取消</button></div>
  </form></div>

  <div v-if="importOpen" class="modal" @click.self="importOpen=false"><form class="mbox live-import" @submit.prevent="previewImport"><h3>导入直播源</h3><div class="fi"><label>读取本地 M3U / TXT</label><input type="file" accept=".m3u,.m3u8,.txt" @change="readFile" /></div><div class="fi"><label>订阅地址（与正文二选一）</label><input v-model="importUrl" type="text" placeholder="https://…" @input="importPreview=null" /></div><div class="fi"><label>M3U / TXT 正文</label><textarea v-model="importContent" rows="8" placeholder="#EXTM3U&#10;#EXTINF:-1 tvg-id=&quot;…&quot; group-title=&quot;香港&quot;,翡翠台&#10;https://…/index.m3u8" @input="importPreview=null" /></div><p class="hint">仅接入 HTTP／HTTPS HLS。导入预览会显示不支持的协议和无法识别的行。</p><p v-if="formError" class="live-admin-error">{{formError}}</p><section v-if="importPreview" class="live-import-preview"><b>识别频道 {{importPreview.channels || 0}} · 线路 {{importPreview.streams || 0}} · 分组 {{Array.isArray(importPreview.groups)?importPreview.groups.length:(importPreview.groups || 0)}}</b><pre v-if="importPreview.sample">{{formatSample(importPreview.sample)}}</pre><p v-for="(item,index) in importPreview.warnings || []" :key="index" class="live-small-error">{{item}}</p></section><div class="form-actions"><button class="btn plain" :disabled="busy">{{busy?'正在读取…':'预览解析结果'}}</button><button v-if="importPreview" type="button" class="btn" :disabled="busy || isActiveJob" @click="executeImport">确认导入并检测</button><button type="button" class="btn plain" @click="importOpen=false">取消</button></div></form></div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { Message, Modal } from '@arco-design/web-vue';
import { defHttp } from '@/utils/http';
import LiveProvider from './live-provider.vue';
const props = defineProps<{ actions: Record<string,boolean> }>();
type Tab = 'channels' | 'groups' | 'streams' | 'subscriptions' | 'provider';
type Kind = 'channel' | 'group' | 'stream' | 'subscription';
type Item = Record<string,any> & {id:number;name:string};
interface LiveJob {id?:number;status:string;total?:number;processed?:number;added?:number;updated?:number;failed?:number;message?:string}
const tabs:{key:Tab;name:string}[]=[{key:'channels',name:'频道'},{key:'groups',name:'分组'},{key:'streams',name:'线路'},{key:'subscriptions',name:'订阅'},{key:'provider',name:'来源与接入'}];
const tab=ref<Tab>('channels'),groups=ref<Item[]>([]),channels=ref<Item[]>([]),streams=ref<Item[]>([]),subscriptions=ref<Item[]>([]);
const page=ref(1),size=30,total=ref(0),query=ref(''),groupFilter=ref(0),loading=ref(false),busy=ref(false),probing=ref(0),error=ref(''),formError=ref('');
const selectedChannel=ref<Item|null>(null),editing=ref<{kind:Kind;id:number;data:Record<string,any>}|null>(null),aliasesText=ref(''),headersText=ref('');
const importOpen=ref(false),importUrl=ref(''),importContent=ref(''),importPreview=ref<Record<string,any>|null>(null),job=ref<LiveJob|null>(null);
let poll:number|undefined,disposed=false,listGeneration=0;
const activeStatuses=['pending','queued','running','detecting','refreshing'];
const isActiveJob=computed(()=>!!job.value && activeStatuses.includes(job.value.status));
const can=(action:string)=>!!props.actions['live/'+action];
const get=(path:string,params:Record<string,any>={})=>defHttp.get({url:'/suxinvideo/live/'+path,params});
const post=(path:string,params:Record<string,any>)=>defHttp.post({url:'/suxinvideo/live/'+path,params});
const kindLabel=(kind:Kind)=>({channel:'频道',group:'分组',stream:'线路',subscription:'订阅'}[kind]);
const healthLabel=(value:string)=>({healthy:'可用',unhealthy:'不可用',unavailable:'不可用',pending:'待检测',unknown:'待检测',checking:'检测中'} as Record<string,string>)[value] || '待检测';
const jobLabel=(value:string)=>({pending:'等待执行',queued:'等待执行',running:'正在执行',detecting:'正在检测',refreshing:'正在刷新',completed:'已完成',done:'已完成',success:'已完成',partial:'部分完成',interrupted:'任务中断',failed:'执行失败',cancelled:'已取消'} as Record<string,string>)[value] || value;
const visibleTabs=computed(()=>tabs.filter(item=>can(item.key==='provider'?'provider/status':item.key)));
function dateLabel(value:any){const number=Number(value);if(!value || number===0)return '尚未执行';if(Number.isFinite(number))return new Date(number<1e12?number*1000:number).toLocaleString();return String(value);}
function formatSample(value:any){return typeof value==='string'?value:JSON.stringify(value,null,2);}
function showError(e:any){error.value=e.message || '操作失败，请重试';}
async function loadGroups(){if(!can('groups'))return;try{const data=await get('groups');groups.value=data.list || [];}catch(e){showError(e);}}
async function loadSubscriptions(){if(!can('subscriptions'))return;try{const data=await get('subscriptions');subscriptions.value=data.list || [];}catch(e){showError(e);}}
async function loadChannels(){if(!can('channels'))return;const generation=++listGeneration;loading.value=true;error.value='';try{const data=await get('channels',{group_id:groupFilter.value,q:query.value,page:page.value,size});if(generation!==listGeneration || disposed)return;channels.value=data.list || [];total.value=Number(data.total || 0);}catch(e){if(generation===listGeneration)showError(e);}finally{if(generation===listGeneration)loading.value=false;}}
async function loadStreams(){if(!can('streams'))return;if(!selectedChannel.value){streams.value=[];return;}try{const id=selectedChannel.value.id;const data=await get('streams',{channel_id:id});if(selectedChannel.value?.id===id)streams.value=data.list || [];}catch(e){showError(e);}}
function setTab(next:Tab){tab.value=next;error.value='';if(next==='groups')loadGroups();if(next==='channels')loadChannels();if(next==='subscriptions')loadSubscriptions();if(next==='streams')loadStreams();}
function showStreams(channel:Item){selectedChannel.value=channel;tab.value='streams';loadStreams();}
function edit(kind:Kind,item?:Item){const data:Record<string,any>={name:'',enabled:true,sort:0,group_id:groups.value.find(group=>group.enabled)?.id || 0,tvg_id:'',logo:'',priority:0,url:'',channel_id:selectedChannel.value?.id || 0,...(item || {})};data.enabled=!!data.enabled;editing.value={kind,id:item?.id || 0,data};aliasesText.value=Array.isArray(data.aliases)?data.aliases.join('\n'):String(data.aliases || '');headersText.value='';formError.value='';}
async function reload(){await loadGroups();if(tab.value==='channels')await loadChannels();else if(tab.value==='streams')await loadStreams();else if(tab.value==='subscriptions')await loadSubscriptions();}
async function save(){if(!editing.value || busy.value)return;busy.value=true;formError.value='';try{const {kind,id,data}=editing.value;const values:Record<string,any>={name:data.name.trim(),enabled:data.enabled};if(kind==='group' || kind==='channel')values.sort=data.sort;if(kind==='channel'){if(!data.group_id)throw Error('请先添加或选择直播分组');Object.assign(values,{group_id:data.group_id,tvg_id:data.tvg_id.trim(),logo:data.logo.trim(),aliases:aliasesText.value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)});}if(kind==='stream' || kind==='subscription')values.url=data.url.trim();if(kind==='stream'){Object.assign(values,{channel_id:data.channel_id,priority:data.priority});if(headersText.value.trim()){const headers=JSON.parse(headersText.value);if(!headers || Array.isArray(headers) || typeof headers!=='object' || Object.values(headers).some(value=>typeof value!=='string'))throw Error('请求头应为 JSON 对象，值须为字符串');values.headers=headers;}}const result=await post('save',{kind,id,data:values});editing.value=null;Message.success('已保存');if(result.job_id)beginJob(result);if(result.message)Message.info(result.message);await reload();}catch(e:any){formError.value=e.message || '保存失败';}finally{busy.value=false;}}
function remove(kind:Kind,item:Item){Modal.confirm({title:'确认停用'+kindLabel(kind)+'？',content:'将停用“'+item.name+'”并保留记录；编辑时可重新启用。手动停用不会被订阅刷新恢复。停用分组或频道后，对应内容不再公开播放。',onOk:async()=>{try{await post('delete',{kind,id:item.id});Message.success('已停用，记录已保留');await reload();}catch(e){showError(e);}}});}
async function probe(item:Item){if(probing.value)return;probing.value=item.id;error.value='';try{const data=await post('probe',{stream_id:item.id});Message.info(data.message || (data.healthy || data.health==='healthy'?'线路检测通过':'检测完成，请查看线路状态'));await loadStreams();}catch(e){showError(e);await loadStreams();}finally{probing.value=0;}}
function openImport(){importOpen.value=true;importPreview.value=null;formError.value='';}
async function readFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;formError.value='';if(file.size>8*1024*1024){formError.value='清单不得超过 8MB';return;}importContent.value=await file.text();importUrl.value='';importPreview.value=null;}
function importPayload(){const url=importUrl.value.trim(),content=importContent.value.trim();if(!url && !content)throw Error('请选择文件、填写正文或订阅地址');if(url && content)throw Error('订阅地址与正文请只填其中一项');return url?{url}:{content};}
async function previewImport(){if(busy.value)return;busy.value=true;formError.value='';try{importPreview.value=await post('import',{...importPayload(),preview:true});}catch(e:any){formError.value=e.message || '解析失败';}finally{busy.value=false;}}
async function executeImport(){if(busy.value || isActiveJob.value)return;busy.value=true;formError.value='';try{const data=await post('import',{...importPayload(),preview:false});importOpen.value=false;beginJob(data);Message.success('已创建导入任务');}catch(e:any){formError.value=e.message || '导入失败';}finally{busy.value=false;}}
async function refresh(subscriptionId:number){if(busy.value || isActiveJob.value)return;busy.value=true;error.value='';try{beginJob(await post('refresh',{subscription_id:subscriptionId}));Message.success('已开始刷新订阅');}catch(e){showError(e);}finally{busy.value=false;}}
function beginJob(data:any){job.value={id:Number(data.job_id || data.id),status:data.status || 'pending',message:'任务已创建，正在读取清单'};try{localStorage.setItem('sx_live_admin_job',String(job.value.id));}catch(_){}schedulePoll(300);}
function schedulePoll(delay=1500){window.clearTimeout(poll);if(!disposed)poll=window.setTimeout(pollJob,delay);}
async function pollJob(){if(disposed || !job.value?.id || !can('job'))return;try{const data=await get('job',{id:job.value.id});if(disposed)return;job.value=data.job || data;if(isActiveJob.value)schedulePoll();else{try{localStorage.removeItem('sx_live_admin_job');}catch(_){}await reload();}}catch(e:any){if(disposed)return;error.value=e.message || '读取进度失败，正在重试';schedulePoll(4000);}}
onMounted(async()=>{tab.value=visibleTabs.value[0]?.key || 'channels';await Promise.all([loadGroups(),loadChannels(),loadSubscriptions()]);if(can('job')){let id=0;try{id=Number(localStorage.getItem('sx_live_admin_job') || 0);}catch(_){}if(id){job.value={id,status:'pending'};pollJob();}}});
onUnmounted(()=>{disposed=true;window.clearTimeout(poll);listGeneration++;});
</script>

<style scoped>
.live-admin-head{display:flex;justify-content:space-between;align-items:flex-start;gap:15px;margin-bottom:15px}.live-admin-head h2{margin:0 0 8px;font-size:19px}.live-admin-head>a{flex:none}.live-table-ops{white-space:nowrap}.live-table-ops .btn{margin:3px}.live-channel-name{display:flex;align-items:center;gap:10px;min-width:150px}.live-channel-name img{width:35px;height:35px;object-fit:contain}.live-stream-url{max-width:360px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;color:var(--sub);margin-top:6px}.live-small-error{font-size:11px;color:#b42318;max-width:360px;overflow-wrap:anywhere;margin-top:5px}.live-admin-error{background:#fff1ef;color:#b42318;padding:10px 13px;border-radius:7px;font-size:13px;overflow-wrap:anywhere}.live-pagination{display:flex;gap:12px;justify-content:center;align-items:center;margin-top:16px;font-size:12px}.live-job{display:flex;flex-wrap:wrap;align-items:center;gap:10px;padding:13px;border:1px solid #dbe6ff;background:#f5f8ff;border-radius:8px;margin:15px 0}.live-job>span{font-size:12px;flex:1}.live-job progress{width:100%;height:9px;accent-color:var(--red)}.live-job small{color:var(--sub)}.live-import{max-width:730px!important}.live-import-preview{padding:12px;background:#f6f7fa;border-radius:7px;margin-bottom:15px;font-size:12px}.live-import-preview pre{max-height:180px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere}.live-editor .form-actions,.live-import .form-actions{margin-top:18px;flex-wrap:wrap}.live-editor input[type=checkbox]{width:auto}.live-admin .searchbar input{max-width:260px}@media(max-width:600px){.live-admin-head{flex-wrap:wrap}.live-pagination{gap:8px}.live-stream-url{max-width:220px}}
</style>
