<template>
  <div class="provider-admin">
    <p class="hint">公共源向游客开放。会员实例的账号由管理员配置，观看权限按会员编号和来源模块授权。</p>
    <div class="tabs"><button v-for="item in tabs" :key="item.key" :class="{on:tab===item.key}" @click="changeTab(item.key)">{{item.label}}</button></div>
    <p v-if="error" class="error" role="alert">{{error}}</p>
    <template v-if="tab==='modules'">
      <div class="toolbar"><button class="btn plain" :disabled="busy" @click="loadStatus">刷新状态</button><template v-if="can('provider/sync')"><button v-for="engine in engines" :key="engine.provider_key" class="btn" :disabled="busy || !canSync(engine)" :title="syncHint(engine)" @click="sync(engine.provider_key)">同步{{engine.provider_key==='public'?'公共':'会员'}}源</button></template></div>
      <p v-if="!hasEnabledMemberModule" class="hint">会员源尚未启用。请先配置并启用需要的会员模块，或通过该模块支持的登录方式启用；实例就绪后即可同步。</p>
      <p v-if="notice" class="notice" role="status" aria-live="polite">{{notice}}</p>
      <div class="engines"><div v-for="engine in engines" :key="engine.provider_key"><b>{{engine.provider_key==='public'?'公共实例':'会员实例'}}</b><span>{{engineState(engine)}}</span><small v-if="engine.ready && engine.health">{{engine.health.channel_count || 0}} 个来源频道<span v-if="!engine.health.channel_count"> · 尚无目录，可同步来源</span></small></div></div>
      <div v-if="job" class="job" role="status"><b>{{job.status==='running'?'正在同步':job.status==='completed'?'同步完成':job.status}}</b><p>{{job.message}}</p><progress :max="Math.max(1,job.total || 1)" :value="job.processed || 0"/><small>{{job.processed || 0}} / {{job.total || 0}} · 新增 {{job.added || 0}} · 失败 {{job.failed || 0}}</small></div>
      <div class="tb-wrap"><table class="tb"><thead><tr><th>模块</th><th>实例</th><th>启用</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="module in modules" :key="module.id"><td><b>{{module.name}}</b><small>{{module.module_key}}</small></td><td>{{module.provider_key==='public'?'公共':'会员'}}</td><td>{{module.enabled?'启用':'停用'}}</td><td>{{module.status}}<small>{{module.last_error}}</small></td><td><button v-if="can('provider/save')" class="btn plain sm" :disabled="busy" @click="editModule(module)">配置</button><button v-if="module.provider_key==='member' && can('provider/login') && supportsLogin(module)" class="btn plain sm" :disabled="busy" @click="openLogin(module)">账号登录</button><small v-if="module.provider_key==='member'">{{loginMethodHint(module)}}</small></td></tr></tbody></table></div>
    </template>
    <template v-else-if="tab==='members'">
      <form v-if="can('members/save')" class="toolbar" @submit.prevent="saveMember"><input v-model.number="memberForm.member_id" type="number" min="1" required placeholder="会员编号"/><select v-model="memberForm.module_key" required><option value="" disabled>选择会员来源模块</option><option v-for="m in memberModules" :key="m.module_key" :value="m.module_key">{{m.name}}</option></select><button class="btn" :disabled="busy">授权</button></form>
      <table class="tb"><thead><tr><th>会员</th><th>模块</th><th>授权</th><th>操作</th></tr></thead><tbody><tr v-for="item in members" :key="item.id"><td>{{item.name}} · {{item.member_id}}</td><td>{{item.module_key}}</td><td>{{item.enabled?'有效':'已撤销'}}</td><td><button v-if="item.enabled && can('members/delete')" class="btn plain sm" @click="revoke('members/delete',item.id,'会员授权')">撤销</button></td></tr><tr v-if="!members.length"><td colspan="4">暂无授权</td></tr></tbody></table>
    </template>
    <template v-else-if="tab==='profiles'">
      <button v-if="can('profiles/save')" class="btn" @click="newProfile">新建分发配置</button>
      <table class="tb"><thead><tr><th>名称</th><th>模块 / 频道</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in profiles" :key="item.id"><td>{{item.name}}</td><td>{{item.modules?.length?item.modules.join('、'):'全部已授权模块'}}<small>{{item.channel_ids?.length?item.channel_ids.length+' 个指定频道':'全部频道'}}</small></td><td>{{item.enabled?'启用':'停用'}}</td><td><button v-if="can('profiles/save')" class="btn plain sm" @click="editProfile(item)">编辑</button><button v-if="can('profiles/delete') && item.enabled" class="btn plain sm" @click="revoke('profiles/delete',item.id,'分发配置')">停用</button></td></tr></tbody></table>
    </template>
    <template v-else-if="tab==='distribution'">
      <form v-if="can('distribution/save')" class="toolbar" @submit.prevent="createSubscription"><input v-model="subscriptionForm.name" required placeholder="订阅名称"/><input v-model.number="subscriptionForm.member_id" min="1" type="number" required placeholder="会员编号"/><select v-model.number="subscriptionForm.profile_id" required><option :value="0" disabled>选择分发配置</option><option v-for="p in profiles.filter(p=>p.enabled)" :key="p.id" :value="p.id">{{p.name}}</option></select><input v-model="subscriptionExpires" type="datetime-local" aria-label="过期时间（可选）"/><button class="btn" :disabled="busy">创建订阅</button></form>
      <div v-if="newSubscription" class="token" role="status"><b>新订阅地址</b><p>复制后请妥善保存；重新生成会立即撤销旧地址。</p><label v-for="(address,format) in newSubscription.urls" :key="format">{{format}}<input :value="absolute(address)" readonly @focus="($event.target as HTMLInputElement).select()"/><button class="btn plain sm" @click="copy(address)">复制</button></label></div>
      <table class="tb"><thead><tr><th>订阅</th><th>会员 / 配置</th><th>状态 / 到期</th><th>操作</th></tr></thead><tbody><tr v-for="item in distributions" :key="item.id"><td>{{item.name}}</td><td>{{item.member_name || item.member_id}} / {{item.profile_name}}</td><td>{{item.enabled?'有效':'已撤销'}}<small>{{item.expires_at?dateTime(item.expires_at):'未设到期日'}}</small></td><td><button v-if="can('distribution/save')" class="btn plain sm" @click="resetSubscription(item)">重新生成</button><button v-if="item.enabled && can('distribution/revoke')" class="btn plain sm" @click="revoke('distribution/revoke',item.id,'订阅')">撤销</button></td></tr></tbody></table>
    </template>
    <template v-else-if="tab==='bindings'">
      <div class="toolbar"><select v-model="bindingKey"><option value="public">公共实例</option><option value="member">会员实例</option></select><button class="btn plain" :disabled="busy" @click="loadBindings">预览频道匹配</button></div><p class="hint">同名和节目单标识可能不同。确认绑定后，来源线路归入所选现有频道。</p>
      <div class="tb-wrap"><table class="tb"><thead><tr><th>来源频道</th><th>当前匹配</th><th>绑定频道</th><th>操作</th></tr></thead><tbody><tr v-for="item in bindings" :key="item.module_key+item.provider_ref"><td>{{item.name}}<small>{{item.module_key}} · {{item.epg_id}}</small></td><td>{{item.binding?.channel_name || item.matches?.map((c:any)=>c.name).join('、') || '新频道'}}<b v-if="item.conflict" class="error">需要确认</b></td><td><select v-model.number="item.selected"><option :value="0">选择现有频道</option><option v-for="c in bindingChannels" :key="c.id" :value="c.id">{{c.name}} · {{c.id}}</option></select></td><td><button v-if="can('provider/bindings/save')" class="btn plain sm" :disabled="!item.selected || busy" @click="saveBinding(item)">绑定</button></td></tr></tbody></table></div>
    </template>
    <template v-else-if="tab==='epg'"><form class="toolbar" @submit.prevent="loadEpg"><input v-model.number="epgChannel" type="number" min="1" required placeholder="频道编号"/><input v-model="epgDate" type="date" required/><button class="btn plain">读取节目单</button></form><p class="hint">节目单只展示上游实际提供的节目。回看是否可用由来源线路决定。</p><table class="tb"><thead><tr><th>节目</th><th>开始</th><th>结束</th><th>回看来源能力</th></tr></thead><tbody><tr v-for="p in programmes" :key="p.id"><td>{{p.title}}</td><td>{{dateTime(p.start)}}</td><td>{{dateTime(p.stop)}}</td><td>{{p.kind==='catchup'?'支持回看':'仅直播'}}</td></tr><tr v-if="!programmes.length"><td colspan="4">此日期暂无节目单</td></tr></tbody></table></template>

    <div v-if="moduleForm" class="modal" @click.self="!busy && (moduleForm=null)"><form class="mbox" @submit.prevent="saveModule"><h3>{{moduleForm.name}} · {{moduleForm.provider_key==='public'?'公共':'会员'}}实例</h3><p v-if="moduleForm.provider_key==='member'" class="hint">{{loginMethodHint(moduleForm)}}</p><p v-if="moduleForm.provider_key==='member' && moduleForm.module_key==='migu'" class="hint">在本人浏览器登录咪咕后，打开开发者工具 → Application → Cookies，找到 UserInfo 值。按 | 分隔后，前两段分别填入账号 ID 和 Token。账号档位和官方授权决定实际画质。</p><label><input v-model="moduleForm.enabled" type="checkbox" :disabled="busy"/>启用此模块</label><div v-for="field in moduleFields" :key="field.key" class="fi"><label>{{field.label || field.key}}</label><select v-if="field.type==='select' || field.type==='multiselect'" v-model="moduleForm.config[field.key]" :multiple="field.type==='multiselect'" :disabled="busy"><option v-for="o in field.options || []" :key="String(o.value)" :value="o.value">{{o.label}}</option></select><input v-else-if="field.type==='boolean'" v-model="moduleForm.config[field.key]" type="checkbox" :disabled="busy"/><textarea v-else-if="field.type==='textarea'" v-model="moduleForm.config[field.key]" rows="4" :disabled="busy"/><input v-else v-model="moduleForm.config[field.key]" :type="field.secret?'password':['number','int'].includes(field.type)?'number':'text'" :min="field.min" :max="field.max" :step="field.type==='int'?1:undefined" :disabled="busy" :autocomplete="field.secret?'new-password':'off'" :placeholder="field.secret?'留空保留已有凭据':''"/><p class="hint">{{field.hint}}</p></div><p v-if="!moduleFields.length" class="hint">此模块使用默认配置。</p><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="busy && notice" class="notice" role="status">{{notice}}</p><div class="toolbar"><button class="btn" :disabled="busy">{{busy?'正在保存…':'保存'}}</button><button type="button" class="btn plain" :disabled="busy" @click="moduleForm=null">取消</button></div></form></div>
    <div v-if="profileForm" class="modal" @click.self="profileForm=null"><form class="mbox" @submit.prevent="saveProfile"><h3>分发配置</h3><div class="fi"><label>名称</label><input v-model="profileForm.name" required maxlength="120"/></div><div class="fi"><label>来源模块（可多选，留空为全部已授权模块）</label><select v-model="profileForm.modules" multiple size="8"><option v-for="m in modules" :key="m.id" :value="m.provider_key+':'+m.module_key">{{m.provider_key==='public'?'公共':'会员'}} · {{m.name}}</option></select></div><div class="fi"><label>限定频道编号（逗号分隔，留空为全部）</label><input v-model="profileChannels" placeholder="例如：1,2,3"/></div><label><input v-model="profileForm.enabled" type="checkbox"/>启用</label><div class="toolbar"><button class="btn" :disabled="busy">保存</button><button type="button" class="btn plain" @click="profileForm=null">取消</button></div></form></div>
    <div v-if="login" class="modal" @click.self="closeLogin"><div class="mbox"><h3>{{login.name}} · 管理员账号登录</h3><p class="hint">账号仅用于会员实例，会员观看仍需单独授权。</p><p class="hint">{{loginMethodHint(login)}}</p><p v-if="!currentLoginModule.enabled" class="notice">{{can('provider/save')?'此模块已停用。开始登录会先启用此模块并准备会员实例。':'此模块已停用。当前账号没有模块配置权限，请联系管理员先启用。'}}</p><p v-else-if="!memberEngineReady" class="notice">会员实例正在准备。开始登录时会等待实例就绪；检查已有登录状态需等实例就绪后再操作。</p><p v-if="loginPending" class="notice" role="status" aria-live="polite">{{loginPending}}</p><p v-if="error" class="error" role="alert">{{error}}</p><div class="toolbar"><button v-if="loginMetadata.login" class="btn" :disabled="busy || !canBeginLogin" @click="loginAction('start')">{{currentLoginModule.enabled?'获取登录二维码':'启用并获取登录二维码'}}</button><template v-if="loginMetadata.browser_login"><button class="btn" :disabled="busy || !canBeginLogin" @click="loginAction('browserStart')">{{currentLoginModule.enabled?'打开后台浏览器登录':'启用并打开后台浏览器登录'}}</button><button class="btn plain" :disabled="busy || !canContinueLogin" @click="loginAction('browserCheck')">检查浏览器登录</button><button class="btn plain" :disabled="busy || !canContinueLogin" @click="loginAction('browserClose')">关闭后台浏览器</button></template></div><p v-if="loginMetadata.browser_login" class="hint">登录窗口在服务器桌面打开。远程访问或服务器没有桌面时，请在本人浏览器登录平台官网后导入 Cookie。</p><img v-if="loginData.image" :src="loginData.image" class="qr" alt="管理员登录二维码"/><p>{{loginData.message || loginData.reason || loginData.status}}</p><div v-if="loginData.account"><b>{{loginData.account.nickname}}</b><p>{{loginData.account.type}}</p></div><details v-if="loginMetadata.browser_login"><summary>导入账号 Cookie</summary><div class="fi"><label>本人账号 Cookie 请求头</label><p class="hint">在央视频官网确认右上角显示昵称后，打开开发者工具 → Network，选择官网请求，复制 Request Headers 中完整的 Cookie 值。仅复制 document.cookie 可能缺少登录凭据。</p><textarea v-model="loginCookie" rows="3" autocomplete="off" maxlength="16384" :disabled="busy" placeholder="粘贴完整 Cookie 请求头内容，导入后立即清空"/></div><button class="btn plain" :disabled="busy || !canBeginLogin || !loginCookie.trim()" @click="loginAction('browserImport')">{{currentLoginModule.enabled?'导入登录态':'启用并导入登录态'}}</button></details><div class="toolbar"><button v-if="loginMetadata.login && loginData.key" class="btn plain" :disabled="busy || !canContinueLogin" @click="loginAction('poll')">检查扫码状态</button><button class="btn plain" @click="closeLogin">关闭</button></div></div></div>
  </div>
</template>

<script setup lang="ts">
import { computed,onMounted,onUnmounted,ref } from 'vue';
import { Message,Modal } from '@arco-design/web-vue';
import { defHttp } from '@/utils/http';
const props=defineProps<{actions:Record<string,boolean>}>();
const can=(action:string)=>!!props.actions['live/'+action];
const get=(path:string,params:Record<string,any>={})=>defHttp.get({url:'/suxinvideo/live/'+path,params});
const post=(path:string,params:Record<string,any>)=>defHttp.post({url:'/suxinvideo/live/'+path,params});
const tabs=computed(()=>[{key:'modules',label:'来源模块',action:'provider/status'},{key:'members',label:'会员授权',action:'members'},{key:'profiles',label:'分发配置',action:'profiles'},{key:'distribution',label:'订阅地址',action:'distribution'},{key:'bindings',label:'频道绑定',action:'provider/bindings'},{key:'epg',label:'节目单',action:'epg'}].filter(t=>can(t.action)));
const tab=ref('modules'),error=ref(''),notice=ref(''),busy=ref(false),engines=ref<any[]>([]),modules=ref<any[]>([]),members=ref<any[]>([]),profiles=ref<any[]>([]),distributions=ref<any[]>([]),job=ref<any>(null);
const moduleForm=ref<any>(null),profileForm=ref<any>(null),profileChannels=ref(''),login=ref<any>(null),loginData=ref<any>({}),newSubscription=ref<any>(null);
const loginCookie=ref(''),loginPending=ref('');
const jobStorage='suxinvideo-live-provider-job';
const memberForm=ref({member_id:undefined as number|undefined,module_key:''}),subscriptionForm=ref({name:'直播订阅',member_id:undefined as number|undefined,profile_id:0}),subscriptionExpires=ref('');
const bindingKey=ref('public'),bindings=ref<any[]>([]),bindingChannels=ref<any[]>([]),epgChannel=ref<number>(),epgDate=ref(new Date().toLocaleDateString('en-CA')),programmes=ref<any[]>([]);
const memberModules=computed(()=>modules.value.filter(m=>m.provider_key==='member'));
const hasEnabledMemberModule=computed(()=>memberModules.value.some(m=>m.enabled));
const memberEngineReady=computed(()=>!!engines.value.find(e=>e.provider_key==='member')?.ready);
const currentLoginModule=computed(()=>modules.value.find(m=>m.id===login.value?.id) || login.value || {});
const loginMetadata=computed(()=>metadataFor(currentLoginModule.value));
const canBeginLogin=computed(()=>can('provider/login') && (currentLoginModule.value.enabled || can('provider/save')));
const canContinueLogin=computed(()=>can('provider/login') && currentLoginModule.value.enabled && memberEngineReady.value);
const moduleFields=computed(()=>moduleForm.value?fieldsFor(moduleForm.value):[]);
let poll:number|undefined,disposed=false,loginGeneration=0;
function metadataFor(item:any){const engine=engines.value.find(e=>e.provider_key===item?.provider_key);return engine?.available_modules?.find((m:any)=>m.id===item?.module_key) || engines.value.find(e=>e.provider_key==='public')?.available_modules?.find((m:any)=>m.id===item?.module_key) || {}}
function fieldsFor(item:any){return (metadataFor(item).config_schema || []).filter((f:any)=>!f.hidden && (item.provider_key==='member'||!f.secret))}
function supportsLogin(item:any){const metadata=metadataFor(item);return !!(metadata.login || metadata.browser_login)}
function loginMethodHint(item:any){const metadata=metadataFor(item);if(metadata.login && metadata.browser_login)return '支持扫码登录、后台浏览器登录或 Cookie 导入。';if(metadata.login)return '支持扫码登录；也可在配置中填写已有凭据。';if(metadata.browser_login)return '支持后台浏览器登录或 Cookie 导入。';if(item.module_key==='migu-sports')return '赛事账号沿用会员实例的咪咕配置，请在咪咕模块填写账号凭据。';if(item.module_key==='migu')return '咪咕不提供扫码或浏览器登录，请在「配置」中填写账号 ID 和 Token；留空使用游客身份。';if(fieldsFor(item).some((f:any)=>f.secret))return '此模块不提供扫码或浏览器登录，请在「配置」中填写账号凭据。';return '此模块没有账号登录入口。'}
function canSync(engine:any){return !!engine.ready && (engine.provider_key!=='member' || hasEnabledMemberModule.value)}
function syncHint(engine:any){if(engine.provider_key==='member' && !hasEnabledMemberModule.value)return '请先配置并启用一个会员模块';return engine.ready?'同步来源目录与节目单':'实例尚未就绪，请刷新状态后再同步'}
function engineState(engine:any){if(engine.ready)return '已就绪';if(engine.provider_key==='member' && !hasEnabledMemberModule.value)return '尚未启用会员模块';return engine.message || '正在准备实例，请稍候刷新状态'}
function fail(e:any){error.value=e.message || '操作失败，请重试'}
async function action(work:()=>Promise<any>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{return await work()}catch(e){notice.value='';fail(e)}finally{busy.value=false}}
async function loadStatus(){if(!can('provider/status'))return;try{const data=await get('provider/status');engines.value=data.engines || [];modules.value=data.modules || []}catch(e){fail(e)}}
async function loadList(path:string,target:any){if(!can(path))return;try{const data=await get(path);target.value=data.list || []}catch(e){fail(e)}}
function changeTab(key:string){tab.value=key;error.value='';if(key==='modules')loadStatus();else if(key==='members')loadList('members',members);else if(key==='profiles')loadList('profiles',profiles);else if(key==='distribution')loadList('distribution',distributions)}
function editModule(item:any){if(!can('provider/save') || busy.value)return;error.value='';moduleForm.value={...item,enabled:!!item.enabled,config:{...item.config}};for(const f of fieldsFor(item)){if(f.secret)moduleForm.value.config[f.key]='';else if(moduleForm.value.config[f.key]===undefined)moduleForm.value.config[f.key]=f.default;if(f.type==='multiselect' && !Array.isArray(moduleForm.value.config[f.key]))moduleForm.value.config[f.key]=String(moduleForm.value.config[f.key] || '').split(/[\n,，]+/).map((v:string)=>v.trim()).filter(Boolean)}}
async function saveModule(){if(!can('provider/save') || !moduleForm.value)return;await action(async()=>{const item=moduleForm.value;notice.value=item.provider_key==='member' && item.enabled?'正在保存配置并准备会员实例，请稍候…':'正在保存模块配置…';await post('provider/save',{provider_key:item.provider_key,module_key:item.module_key,enabled:item.enabled,config:item.config});moduleForm.value=null;await loadStatus();notice.value=item.provider_key==='member' && item.enabled && !memberEngineReady.value?'配置已保存，会员实例正在准备。请刷新状态，实例就绪后可登录或同步。':'配置已保存';Message.success('配置已保存')})}
async function sync(key:string){if(!can('provider/sync'))return;const engine=engines.value.find(e=>e.provider_key===key);if(!engine || !canSync(engine)){notice.value=syncHint(engine || {provider_key:key});return}await action(async()=>{notice.value='正在创建同步任务，请稍候…';const data=await post('provider/sync',{provider_key:key});job.value={id:data.job_id,status:'pending',message:'同步任务已创建'};notice.value='同步任务已创建';localStorage.setItem(jobStorage,String(data.job_id));schedulePoll();})}
function schedulePoll(){window.clearTimeout(poll);if(!disposed)poll=window.setTimeout(pollJob,1500)}
async function pollJob(){if(disposed||!job.value||!can('job'))return;try{const data=await get('job',{id:job.value.id});job.value=data.job || data;if(['pending','running'].includes(job.value.status))schedulePoll();else{localStorage.removeItem(jobStorage);await loadStatus()}}catch(e){fail(e);schedulePoll()}}
async function saveMember(){await action(async()=>{await post('members/save',{...memberForm.value,enabled:true});Message.success('会员授权已保存');await loadList('members',members)})}
function editProfile(item:any){profileForm.value={...item,enabled:!!item.enabled,modules:[...(item.modules || [])]};profileChannels.value=(item.channel_ids || []).join(',')}
function newProfile(){profileChannels.value='';profileForm.value={id:0,name:'',modules:[],channel_ids:[],enabled:true}}
async function saveProfile(){await action(async()=>{const ids=profileChannels.value.split(/[,，\s]+/).filter(Boolean).map(Number);if(ids.some(id=>!Number.isInteger(id)||id<1))throw Error('频道编号须为正整数');await post('profiles/save',{...profileForm.value,channel_ids:ids});profileForm.value=null;Message.success('分发配置已保存');await loadList('profiles',profiles)})}
async function createSubscription(){await action(async()=>{newSubscription.value=await post('distribution/save',{...subscriptionForm.value,expires_at:subscriptionExpires.value?Math.floor(new Date(subscriptionExpires.value).getTime()/1000):0,enabled:true});await loadList('distribution',distributions)})}
function resetSubscription(item:any){Modal.confirm({title:'重新生成订阅地址？',content:'旧地址及现有订阅播放会话会立即失效。',onOk:()=>action(async()=>{newSubscription.value=await post('distribution/save',{...item,reset:true});await loadList('distribution',distributions)})})}
function revoke(path:string,id:number,label:string){Modal.confirm({title:'撤销'+label+'？',content:'当前授权将立即失效，记录仍会保留。',onOk:()=>action(async()=>{await post(path,{id});await Promise.all([loadList('members',members),loadList('profiles',profiles),loadList('distribution',distributions)])})})}
async function loadBindings(){await action(async()=>{const data=await get('provider/bindings',{provider_key:bindingKey.value});bindings.value=(data.list || []).map((x:any)=>({...x,selected:x.binding?.channel_id || 0}));bindingChannels.value=data.channels || []})}
async function saveBinding(item:any){await action(async()=>{await post('provider/bindings/save',{provider_key:bindingKey.value,module_key:item.module_key,provider_ref:item.provider_ref,channel_id:item.selected});Message.success('频道已绑定');item.binding={channel_id:item.selected,channel_name:bindingChannels.value.find(c=>c.id===item.selected)?.name}})}
async function loadEpg(){await action(async()=>{const start=Math.floor(new Date(epgDate.value+'T00:00:00+08:00').getTime()/1000);const data=await get('epg',{channel_id:epgChannel.value,start,end:start+86400});programmes.value=data.items || []})}
function openLogin(item:any){if(!can('provider/login') || !supportsLogin(item) || busy.value)return;loginGeneration++;error.value='';login.value=item;loginData.value={};loginCookie.value='';loginPending.value=''}
async function loginAction(type:string){if(!login.value || !can('provider/login'))return;const begin=['start','browserStart','browserImport'].includes(type);const supported=['start','poll'].includes(type)?loginMetadata.value.login:loginMetadata.value.browser_login;if(!supported || (begin?!canBeginLogin.value:!canContinueLogin.value))return;const item=currentLoginModule.value,generation=loginGeneration;await action(async()=>{const payload=type==='browserImport'?loginCookie.value:undefined;loginPending.value=begin && !item.enabled?'正在启用模块并准备会员实例，随后开始登录，请稍候…':begin && !memberEngineReady.value?'正在等待会员实例就绪，随后开始登录，请稍候…':type==='browserImport'?'正在导入并验证登录态，请稍候…':type==='browserStart'?'正在打开服务器登录窗口，请稍候…':type==='start'?'正在获取登录二维码，请稍候…':'正在读取登录状态，请稍候…';try{const data=await post('provider/login',{module_key:item.module_key,action:type,key:loginData.value.key || '',payload});if(disposed || generation!==loginGeneration)return;loginData.value={...loginData.value,...(data.data || data)};if(type==='poll' && ['ok','expired','failed'].includes(loginData.value.status)){delete loginData.value.key;delete loginData.value.image}await loadStatus()}catch(e){if(disposed || generation!==loginGeneration)return;throw e}finally{if(generation===loginGeneration){loginPending.value='';if(type==='browserImport')loginCookie.value=''}}})}
function closeLogin(){loginGeneration++;login.value=null;loginData.value={};loginCookie.value='';loginPending.value='';error.value=''}
function absolute(path:string){return new URL(path,window.location.origin).href}
async function copy(path:string){try{await navigator.clipboard.writeText(absolute(path));Message.success('已复制')}catch(_){Message.info('请选择并复制订阅地址')}}
function dateTime(seconds:number){return new Date(seconds*1000).toLocaleString()}
onMounted(async()=>{tab.value=tabs.value[0]?.key || 'modules';const pending=Number(localStorage.getItem(jobStorage));if(pending>0 && can('job')){job.value={id:pending,status:'pending',message:'正在恢复同步进度'};schedulePoll()}await Promise.all([loadStatus(),loadList('members',members),loadList('profiles',profiles),loadList('distribution',distributions)])});
onUnmounted(()=>{disposed=true;loginGeneration++;loginCookie.value='';window.clearTimeout(poll)});
</script>

<style scoped>
.provider-admin{padding-top:10px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:16px 0}.toolbar input,.toolbar select{max-width:230px}.engines{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}.engines>div{display:grid;gap:8px;padding:14px;background:var(--bg,#f5f7fa);border-radius:8px;min-width:210px}.notice{color:#174ea6;background:#edf4ff;padding:10px;border-radius:6px}.error{color:#b42318;background:#fff1ef;padding:10px;border-radius:6px}.tb small{display:block;color:var(--sub);margin-top:5px}.tb .btn{margin:3px}.tb select{max-width:220px}.job{padding:12px;background:#f0f5ff;border-radius:8px}.job progress{width:100%;display:block}.token{padding:16px;background:#f0f7ff;border-radius:8px;margin:16px 0}.token label{display:flex;gap:9px;align-items:center;margin-top:10px}.token input{flex:1;min-width:100px}.mbox{max-width:620px;max-height:90vh;overflow:auto}.fi{margin:15px 0}.fi input,.fi select,.fi textarea{width:100%}.fi input[type=checkbox],.mbox>form input[type=checkbox]{width:auto}.qr{display:block;max-width:260px;margin:20px auto}.tb{margin-top:15px}@media(max-width:600px){.token label{flex-wrap:wrap}.toolbar input,.toolbar select{max-width:100%}}
</style>
