// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxArticleDao is the data access object for the table sx_article.
// You can define custom methods on it to extend its functionality as needed.
type sxArticleDao struct {
	*internal.SxArticleDao
}

var (
	// SxArticle is a globally accessible object for table sx_article operations.
	SxArticle = sxArticleDao{internal.NewSxArticleDao()}
)

// Add your custom methods and functionality below.
