// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxLinkDao is the data access object for the table sx_link.
// You can define custom methods on it to extend its functionality as needed.
type sxLinkDao struct {
	*internal.SxLinkDao
}

var (
	// SxLink is a globally accessible object for table sx_link operations.
	SxLink = sxLinkDao{internal.NewSxLinkDao()}
)

// Add your custom methods and functionality below.
