// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxPluginDao is the data access object for the table sx_plugin.
// You can define custom methods on it to extend its functionality as needed.
type sxPluginDao struct {
	*internal.SxPluginDao
}

var (
	// SxPlugin is a globally accessible object for table sx_plugin operations.
	SxPlugin = sxPluginDao{internal.NewSxPluginDao()}
)

// Add your custom methods and functionality below.
