// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxSignDao is the data access object for the table sx_sign.
// You can define custom methods on it to extend its functionality as needed.
type sxSignDao struct {
	*internal.SxSignDao
}

var (
	// SxSign is a globally accessible object for table sx_sign operations.
	SxSign = sxSignDao{internal.NewSxSignDao()}
)

// Add your custom methods and functionality below.
