// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxSlideDao is the data access object for the table sx_slide.
// You can define custom methods on it to extend its functionality as needed.
type sxSlideDao struct {
	*internal.SxSlideDao
}

var (
	// SxSlide is a globally accessible object for table sx_slide operations.
	SxSlide = sxSlideDao{internal.NewSxSlideDao()}
)

// Add your custom methods and functionality below.
