// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxUserDao is the data access object for the table sx_user.
// You can define custom methods on it to extend its functionality as needed.
type sxUserDao struct {
	*internal.SxUserDao
}

var (
	// SxUser is a globally accessible object for table sx_user operations.
	SxUser = sxUserDao{internal.NewSxUserDao()}
)

// Add your custom methods and functionality below.
