// =================================================================================
// This is auto-generated by Suxin CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"github.com/suxinwl/GoSuxin/api/admin"
)

type ControllerUser struct{}

func NewUser() admin.IAdminUser {
	return &ControllerUser{}
}

type ControllerSystem struct{}

func NewSystem() admin.IAdminSystem {
	return &ControllerSystem{}
}

type ControllerDashboard struct{}

func NewDashboard() admin.IAdminDashboard {
	return &ControllerDashboard{}
}

type ControllerInstall struct{}

func NewInstall() admin.IAdminInstall {
	return &ControllerInstall{}
}

type ControllerCommon struct{}

func NewCommon() admin.IAdminCommon {
	return &ControllerCommon{}
}

type ControllerDatacenter struct{}

func NewDatacenter() admin.IAdminDatacenter {
	return &ControllerDatacenter{}
}

type ControllerDeveloper struct{}

func NewDeveloper() admin.IAdminDeveloper {
	return &ControllerDeveloper{}
}
