// =================================================================================
// This is auto-generated by Suxin CLI tool only once. Fill this file as you wish.
// =================================================================================

package article

import (
	"github.com/suxinwl/GoSuxin/framework/cmd/suxin/internal/cmd/testdata/genctrl/multi/api/admin/article"
)

type ControllerV1 struct{}

func NewV1() article.IArticleV1 {
	return &ControllerV1{}
}
