app:
  name: privatecode
  title: 私有插件仓
  version: 1.1.5
  isinstall: true
  installcover: false
  isModTidy: false
  commandLines: ""
sqldb:
  packtables: privatecode_cate,privatecode_content,privatecode_release
