app:
     version: 2.5.0
     title: 速信影视CMS
     des: GoSuxin 影视内容管理插件（仅基础数据）
     name: suxinvideo
     isinstall: true
     installcover: false
     isModTidy: true
     commandLines: ""
     goFiles: |
          [
            {"path":"/api/suxinvideo","isDir":true},
            {"path":"/internal/controller/suxinvideo","isDir":true},
            {"path":"/internal/erciyuan","isDir":true},
            {"path":"/internal/yqksign","isDir":true},
            {"path":"/internal/xiaoqiapp","isDir":true},
            {"path":"/internal/mediaplaylist","isDir":true},
            {"path":"/internal/mediastream","isDir":true},
            {"path":"/internal/liveruntime","isDir":true},
            {"path":"/third_party/akiralereal-iptv","isDir":true},
            {"path":"/internal/xiaoqiwebui","isDir":true},
            {"path":"/internal/dao/sx_admin_log.go","isDir":false},
            {"path":"/internal/dao/sx_article.go","isDir":false},
            {"path":"/internal/dao/sx_collect_api.go","isDir":false},
            {"path":"/internal/dao/sx_comment.go","isDir":false},
            {"path":"/internal/dao/sx_config.go","isDir":false},
            {"path":"/internal/dao/sx_email_code.go","isDir":false},
            {"path":"/internal/dao/sx_fav.go","isDir":false},
            {"path":"/internal/dao/sx_film_request.go","isDir":false},
            {"path":"/internal/dao/sx_goods.go","isDir":false},
            {"path":"/internal/dao/sx_link.go","isDir":false},
            {"path":"/internal/dao/sx_login_fail.go","isDir":false},
            {"path":"/internal/dao/sx_order.go","isDir":false},
            {"path":"/internal/dao/sx_play_record.go","isDir":false},
            {"path":"/internal/dao/sx_player.go","isDir":false},
            {"path":"/internal/dao/sx_plugin.go","isDir":false},
            {"path":"/internal/dao/sx_sign.go","isDir":false},
            {"path":"/internal/dao/sx_slide.go","isDir":false},
            {"path":"/internal/dao/sx_topic.go","isDir":false},
            {"path":"/internal/dao/sx_type.go","isDir":false},
            {"path":"/internal/dao/sx_user.go","isDir":false},
            {"path":"/internal/dao/sx_user_vod.go","isDir":false},
            {"path":"/internal/dao/sx_vod.go","isDir":false},
            {"path":"/internal/dao/internal/sx_article.go","isDir":false},
            {"path":"/internal/dao/internal/sx_admin_log.go","isDir":false},
            {"path":"/internal/dao/internal/sx_collect_api.go","isDir":false},
            {"path":"/internal/dao/internal/sx_comment.go","isDir":false},
            {"path":"/internal/dao/internal/sx_config.go","isDir":false},
            {"path":"/internal/dao/internal/sx_email_code.go","isDir":false},
            {"path":"/internal/dao/internal/sx_fav.go","isDir":false},
            {"path":"/internal/dao/internal/sx_film_request.go","isDir":false},
            {"path":"/internal/dao/internal/sx_goods.go","isDir":false},
            {"path":"/internal/dao/internal/sx_link.go","isDir":false},
            {"path":"/internal/dao/internal/sx_login_fail.go","isDir":false},
            {"path":"/internal/dao/internal/sx_order.go","isDir":false},
            {"path":"/internal/dao/internal/sx_play_record.go","isDir":false},
            {"path":"/internal/dao/internal/sx_player.go","isDir":false},
            {"path":"/internal/dao/internal/sx_plugin.go","isDir":false},
            {"path":"/internal/dao/internal/sx_sign.go","isDir":false},
            {"path":"/internal/dao/internal/sx_slide.go","isDir":false},
            {"path":"/internal/dao/internal/sx_topic.go","isDir":false},
            {"path":"/internal/dao/internal/sx_type.go","isDir":false},
            {"path":"/internal/dao/internal/sx_user.go","isDir":false},
            {"path":"/internal/dao/internal/sx_user_vod.go","isDir":false},
            {"path":"/internal/dao/internal/sx_vod.go","isDir":false},
            {"path":"/internal/model/do/sx_article.go","isDir":false},
            {"path":"/internal/model/do/sx_admin_log.go","isDir":false},
            {"path":"/internal/model/do/sx_collect_api.go","isDir":false},
            {"path":"/internal/model/do/sx_comment.go","isDir":false},
            {"path":"/internal/model/do/sx_config.go","isDir":false},
            {"path":"/internal/model/do/sx_email_code.go","isDir":false},
            {"path":"/internal/model/do/sx_fav.go","isDir":false},
            {"path":"/internal/model/do/sx_film_request.go","isDir":false},
            {"path":"/internal/model/do/sx_goods.go","isDir":false},
            {"path":"/internal/model/do/sx_link.go","isDir":false},
            {"path":"/internal/model/do/sx_login_fail.go","isDir":false},
            {"path":"/internal/model/do/sx_order.go","isDir":false},
            {"path":"/internal/model/do/sx_play_record.go","isDir":false},
            {"path":"/internal/model/do/sx_player.go","isDir":false},
            {"path":"/internal/model/do/sx_plugin.go","isDir":false},
            {"path":"/internal/model/do/sx_sign.go","isDir":false},
            {"path":"/internal/model/do/sx_slide.go","isDir":false},
            {"path":"/internal/model/do/sx_topic.go","isDir":false},
            {"path":"/internal/model/do/sx_type.go","isDir":false},
            {"path":"/internal/model/do/sx_user.go","isDir":false},
            {"path":"/internal/model/do/sx_user_vod.go","isDir":false},
            {"path":"/internal/model/do/sx_vod.go","isDir":false},
            {"path":"/internal/model/entity/sx_article.go","isDir":false},
            {"path":"/internal/model/entity/sx_admin_log.go","isDir":false},
            {"path":"/internal/model/entity/sx_collect_api.go","isDir":false},
            {"path":"/internal/model/entity/sx_comment.go","isDir":false},
            {"path":"/internal/model/entity/sx_config.go","isDir":false},
            {"path":"/internal/model/entity/sx_email_code.go","isDir":false},
            {"path":"/internal/model/entity/sx_fav.go","isDir":false},
            {"path":"/internal/model/entity/sx_film_request.go","isDir":false},
            {"path":"/internal/model/entity/sx_goods.go","isDir":false},
            {"path":"/internal/model/entity/sx_link.go","isDir":false},
            {"path":"/internal/model/entity/sx_login_fail.go","isDir":false},
            {"path":"/internal/model/entity/sx_order.go","isDir":false},
            {"path":"/internal/model/entity/sx_play_record.go","isDir":false},
            {"path":"/internal/model/entity/sx_player.go","isDir":false},
            {"path":"/internal/model/entity/sx_plugin.go","isDir":false},
            {"path":"/internal/model/entity/sx_sign.go","isDir":false},
            {"path":"/internal/model/entity/sx_slide.go","isDir":false},
            {"path":"/internal/model/entity/sx_topic.go","isDir":false},
            {"path":"/internal/model/entity/sx_type.go","isDir":false},
            {"path":"/internal/model/entity/sx_user.go","isDir":false},
            {"path":"/internal/model/entity/sx_user_vod.go","isDir":false},
            {"path":"/internal/model/entity/sx_vod.go","isDir":false}
          ]
     vueFiles: '[{"path":"/src/views/suxinvideo","isDir":true}]'
     modellist: "[]"
sqldb:
     packtables: ""
     adminmenuids: ""
