// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// adminDao is the data access object for the table gf_admin.
// You can define custom methods on it to extend its functionality as needed.
type adminDao struct {
	*internal.AdminDao
}

var (
	// Admin is a globally accessible object for table gf_admin operations.
	Admin = adminDao{internal.NewAdminDao()}
)

// Add your custom methods and functionality below.
