// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// attachmentDao is the data access object for the table gf_attachment.
// You can define custom methods on it to extend its functionality as needed.
type attachmentDao struct {
	*internal.AttachmentDao
}

var (
	// Attachment is a globally accessible object for table gf_attachment operations.
	Attachment = attachmentDao{internal.NewAttachmentDao()}
)

// Add your custom methods and functionality below.
