// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// authRoleAccessDao is the data access object for the table gf_auth_role_access.
// You can define custom methods on it to extend its functionality as needed.
type authRoleAccessDao struct {
	*internal.AuthRoleAccessDao
}

var (
	// AuthRoleAccess is a globally accessible object for table gf_auth_role_access operations.
	AuthRoleAccess = authRoleAccessDao{internal.NewAuthRoleAccessDao()}
)

// Add your custom methods and functionality below.
