// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// authRuleDao is the data access object for the table gf_auth_rule.
// You can define custom methods on it to extend its functionality as needed.
type authRuleDao struct {
	*internal.AuthRuleDao
}

var (
	// AuthRule is a globally accessible object for table gf_auth_rule operations.
	AuthRule = authRuleDao{internal.NewAuthRuleDao()}
)

// Add your custom methods and functionality below.
