// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// authDeptDao is the data access object for the table gf_auth_dept.
// You can define custom methods on it to extend its functionality as needed.
type authDeptDao struct {
	*internal.AuthDeptDao
}

var (
	// AuthDept is a globally accessible object for table gf_auth_dept operations.
	AuthDept = authDeptDao{internal.NewAuthDeptDao()}
)

// Add your custom methods and functionality below.
