// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// authRoleDao is the data access object for the table gf_auth_role.
// You can define custom methods on it to extend its functionality as needed.
type authRoleDao struct {
	*internal.AuthRoleDao
}

var (
	// AuthRole is a globally accessible object for table gf_auth_role operations.
	AuthRole = authRoleDao{internal.NewAuthRoleDao()}
)

// Add your custom methods and functionality below.
