// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// dictionaryDataDao is the data access object for the table gf_dictionary_data.
// You can define custom methods on it to extend its functionality as needed.
type dictionaryDataDao struct {
	*internal.DictionaryDataDao
}

var (
	// DictionaryData is a globally accessible object for table gf_dictionary_data operations.
	DictionaryData = dictionaryDataDao{internal.NewDictionaryDataDao()}
)

// Add your custom methods and functionality below.
