// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// dictionaryGroupDao is the data access object for the table gf_dictionary_group.
// You can define custom methods on it to extend its functionality as needed.
type dictionaryGroupDao struct {
	*internal.DictionaryGroupDao
}

var (
	// DictionaryGroup is a globally accessible object for table gf_dictionary_group operations.
	DictionaryGroup = dictionaryGroupDao{internal.NewDictionaryGroupDao()}
)

// Add your custom methods and functionality below.
