// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// emailDao is the data access object for the table gf_email.
// You can define custom methods on it to extend its functionality as needed.
type emailDao struct {
	*internal.EmailDao
}

var (
	// Email is a globally accessible object for table gf_email operations.
	Email = emailDao{internal.NewEmailDao()}
)

// Add your custom methods and functionality below.
