// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// homeQuickopDao is the data access object for the table gf_home_quickop.
// You can define custom methods on it to extend its functionality as needed.
type homeQuickopDao struct {
	*internal.HomeQuickopDao
}

var (
	// HomeQuickop is a globally accessible object for table gf_home_quickop operations.
	HomeQuickop = homeQuickopDao{internal.NewHomeQuickopDao()}
)

// Add your custom methods and functionality below.
