// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// memberDao is the data access object for the table gf_member.
// You can define custom methods on it to extend its functionality as needed.
type memberDao struct {
	*internal.MemberDao
}

var (
	// Member is a globally accessible object for table gf_member operations.
	Member = memberDao{internal.NewMemberDao()}
)

// Add your custom methods and functionality below.
