// =================================================================================
// This file is auto-generated by the Suxin CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// operationLogDao is the data access object for the table gf_operation_log.
// You can define custom methods on it to extend its functionality as needed.
type operationLogDao struct {
	*internal.OperationLogDao
}

var (
	// OperationLog is a globally accessible object for table gf_operation_log operations.
	OperationLog = operationLogDao{internal.NewOperationLogDao()}
)

// Add your custom methods and functionality below.
