// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxAdminLogDao is the data access object for the table sx_admin_log.
// You can define custom methods on it to extend its functionality as needed.
type sxAdminLogDao struct {
	*internal.SxAdminLogDao
}

var (
	// SxAdminLog is a globally accessible object for table sx_admin_log operations.
	SxAdminLog = sxAdminLogDao{internal.NewSxAdminLogDao()}
)

// Add your custom methods and functionality below.
