// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxConfigDao is the data access object for the table sx_config.
// You can define custom methods on it to extend its functionality as needed.
type sxConfigDao struct {
	*internal.SxConfigDao
}

var (
	// SxConfig is a globally accessible object for table sx_config operations.
	SxConfig = sxConfigDao{internal.NewSxConfigDao()}
)

// Add your custom methods and functionality below.
