// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxCommentDao is the data access object for the table sx_comment.
// You can define custom methods on it to extend its functionality as needed.
type sxCommentDao struct {
	*internal.SxCommentDao
}

var (
	// SxComment is a globally accessible object for table sx_comment operations.
	SxComment = sxCommentDao{internal.NewSxCommentDao()}
)

// Add your custom methods and functionality below.
