// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxCollectApiDao is the data access object for the table sx_collect_api.
// You can define custom methods on it to extend its functionality as needed.
type sxCollectApiDao struct {
	*internal.SxCollectApiDao
}

var (
	// SxCollectApi is a globally accessible object for table sx_collect_api operations.
	SxCollectApi = sxCollectApiDao{internal.NewSxCollectApiDao()}
)

// Add your custom methods and functionality below.
