// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxEmailCodeDao is the data access object for the table sx_email_code.
// You can define custom methods on it to extend its functionality as needed.
type sxEmailCodeDao struct {
	*internal.SxEmailCodeDao
}

var (
	// SxEmailCode is a globally accessible object for table sx_email_code operations.
	SxEmailCode = sxEmailCodeDao{internal.NewSxEmailCodeDao()}
)

// Add your custom methods and functionality below.
