// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxFavDao is the data access object for the table sx_fav.
// You can define custom methods on it to extend its functionality as needed.
type sxFavDao struct {
	*internal.SxFavDao
}

var (
	// SxFav is a globally accessible object for table sx_fav operations.
	SxFav = sxFavDao{internal.NewSxFavDao()}
)

// Add your custom methods and functionality below.
