// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxFilmRequestDao is the data access object for the table sx_film_request.
// You can define custom methods on it to extend its functionality as needed.
type sxFilmRequestDao struct {
	*internal.SxFilmRequestDao
}

var (
	// SxFilmRequest is a globally accessible object for table sx_film_request operations.
	SxFilmRequest = sxFilmRequestDao{internal.NewSxFilmRequestDao()}
)

// Add your custom methods and functionality below.
