// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxGoodsDao is the data access object for the table sx_goods.
// You can define custom methods on it to extend its functionality as needed.
type sxGoodsDao struct {
	*internal.SxGoodsDao
}

var (
	// SxGoods is a globally accessible object for table sx_goods operations.
	SxGoods = sxGoodsDao{internal.NewSxGoodsDao()}
)

// Add your custom methods and functionality below.
