// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxOrderDao is the data access object for the table sx_order.
// You can define custom methods on it to extend its functionality as needed.
type sxOrderDao struct {
	*internal.SxOrderDao
}

var (
	// SxOrder is a globally accessible object for table sx_order operations.
	SxOrder = sxOrderDao{internal.NewSxOrderDao()}
)

// Add your custom methods and functionality below.
