// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxPlayerDao is the data access object for the table sx_player.
// You can define custom methods on it to extend its functionality as needed.
type sxPlayerDao struct {
	*internal.SxPlayerDao
}

var (
	// SxPlayer is a globally accessible object for table sx_player operations.
	SxPlayer = sxPlayerDao{internal.NewSxPlayerDao()}
)

// Add your custom methods and functionality below.
