// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxPlayRecordDao is the data access object for the table sx_play_record.
// You can define custom methods on it to extend its functionality as needed.
type sxPlayRecordDao struct {
	*internal.SxPlayRecordDao
}

var (
	// SxPlayRecord is a globally accessible object for table sx_play_record operations.
	SxPlayRecord = sxPlayRecordDao{internal.NewSxPlayRecordDao()}
)

// Add your custom methods and functionality below.
