// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxTopicDao is the data access object for the table sx_topic.
// You can define custom methods on it to extend its functionality as needed.
type sxTopicDao struct {
	*internal.SxTopicDao
}

var (
	// SxTopic is a globally accessible object for table sx_topic operations.
	SxTopic = sxTopicDao{internal.NewSxTopicDao()}
)

// Add your custom methods and functionality below.
