// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxTypeDao is the data access object for the table sx_type.
// You can define custom methods on it to extend its functionality as needed.
type sxTypeDao struct {
	*internal.SxTypeDao
}

var (
	// SxType is a globally accessible object for table sx_type operations.
	SxType = sxTypeDao{internal.NewSxTypeDao()}
)

// Add your custom methods and functionality below.
