// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxUserVodDao is the data access object for the table sx_user_vod.
// You can define custom methods on it to extend its functionality as needed.
type sxUserVodDao struct {
	*internal.SxUserVodDao
}

var (
	// SxUserVod is a globally accessible object for table sx_user_vod operations.
	SxUserVod = sxUserVodDao{internal.NewSxUserVodDao()}
)

// Add your custom methods and functionality below.
