// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/suxinwl/GoSuxin/internal/dao/internal"
)

// sxVodDao is the data access object for the table sx_vod.
// You can define custom methods on it to extend its functionality as needed.
type sxVodDao struct {
	*internal.SxVodDao
}

var (
	// SxVod is a globally accessible object for table sx_vod operations.
	SxVod = sxVodDao{internal.NewSxVodDao()}
)

// Add your custom methods and functionality below.
