package suxinvideo

import (
	"strings"
	"time"

	"github.com/suxinwl/GoSuxin/framework/util/gconv"
)

// Auth pages use the same original site mark as the header, including the
// bundled xiaoqilogo fallback when a configured image cannot be loaded.
const authBrandStyle = `<style>.cms-body .auth h2{display:flex;align-items:center;justify-content:center;gap:10px;line-height:1.4}.cms-body .auth h2 .sx-auth-brand-logo{display:inline-block;width:32px;height:32px;min-width:32px;max-width:32px;object-fit:contain;flex-shrink:0;border-radius:8px;background:#fff}</style>`
const authBrandLogo = `<img class="sx-auth-brand-logo" src="{{if .SiteLogo}}{{.SiteLogo}}{{else}}` + defaultLogoURL + `{{end}}" alt="{{.SiteName}} LOGO" width="32" height="32" onerror="this.onerror=null;this.src='` + defaultLogoURL + `'">`

const authSubmitScript = `<script>(function(){
 const form=document.querySelector('.auth-wrap form.auth');if(!form)return;
 form.addEventListener('submit',async function(event){
  event.preventDefault();const button=form.querySelector('button[type="submit"],button.btn-main');
  const original=button?.textContent||'';if(button)button.disabled=true;
  let result=form.querySelector('.sx-auth-result');if(!result){result=document.createElement('p');result.className='sx-auth-result';result.setAttribute('role','status');result.style.cssText='color:#ef5b58;margin-top:12px;text-align:center';form.appendChild(result)}
  result.textContent='';
  try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),credentials:'same-origin'});
   if(response.redirected){location.assign(response.url);return}
   const message=(await response.text()).trim();
   if(!response.ok)throw Error(message.slice(0,180)||'提交失败，请稍后重试');
   const data=JSON.parse(message);if(data.code!==0&&data.code!==1)throw Error(data.message||data.msg||'提交失败');
   location.assign(data.data?.redirect||'/suxinvideo/center');
  }catch(error){result.textContent=error.message||'网络异常';const captcha=form.querySelector('.sx-captcha-img');if(captcha)captcha.click();if(window.turnstile)window.turnstile.reset()}
  finally{if(button){button.disabled=false;button.textContent=original}}
 });
})();</script>`

const loginThemeBody = authBrandStyle + `<div class="auth-wrap"><form class="auth" method="post" action="/suxinvideo/login"><h2>` + authBrandLogo + `登录{{.SiteName}}</h2><div class="fi"><label>邮箱</label><input class="sx-input" name="email" type="email" required autocomplete="email" placeholder="example@qq.com"></div><div class="fi"><label>密码</label><input class="sx-input" name="password" type="password" required autocomplete="current-password"></div>{{.CaptchaWidget}}<button class="btn-main">登录</button>{{if .RegistrationEnabled}}<a class="btn-line" href="/suxinvideo/register">没有账号？立即注册</a>{{end}}{{if .PasswordResetEnabled}}<a class="btn-line" href="/suxinvideo/forgot">忘记密码？</a>{{end}}<p class="alt">连续登录失败 5 次将暂时锁定账号</p></form></div>` + authSubmitScript

const registerThemeBody = authBrandStyle + `<div class="auth-wrap"><form class="auth" id="register-form" method="post" action="/suxinvideo/register"><h2>` + authBrandLogo + `注册{{.SiteName}}</h2><div class="fi"><label>邮箱</label><input class="sx-input" name="email" type="email" required></div><div class="fi"><label>昵称</label><input class="sx-input" name="name" required></div><div class="fi"><label>密码</label><input class="sx-input" name="password" type="password" minlength="6" required></div>{{if .RegistrationRequiresEmailCode}}<div class="fi"><label>邮箱验证码</label><input class="sx-input" name="email_code" required><button id="send-code" class="btn-line" type="button">发送验证码</button></div>{{end}}{{.CaptchaWidget}}<button type="submit" class="btn-main">立即注册</button><a class="btn-line" href="/suxinvideo/login">已有账号？去登录</a>{{if .RegistrationRequiresEmailCode}}<p id="send-result" role="status"></p>{{end}}</form></div>{{if .RegistrationRequiresEmailCode}}<script>(function(){const form=document.getElementById('register-form'),button=document.getElementById('send-code'),output=document.getElementById('send-result');if(!form||!button||!output)return;button.onclick=async()=>{button.disabled=true;const data=new FormData();data.set('email',form.elements.email.value);['captcha','cf-turnstile-response','lot_number','captcha_output','pass_token','gen_time'].forEach(k=>{if(form.elements[k])data.set(k,form.elements[k].value)});try{const response=await fetch('/suxinvideo/sendcode',{method:'POST',body:data,credentials:'same-origin'}),text=await response.text();let result;try{result=JSON.parse(text)}catch(e){throw Error(text.slice(0,160))}if(!response.ok)throw Error(result.message||result.msg||'发送失败');output.textContent='验证码已发送'}catch(e){output.textContent=e.message}finally{button.disabled=false;const img=document.getElementById('sx-captcha-img');if(img)img.src='/suxinvideo/captcha?t='+Date.now();if(window.turnstile)window.turnstile.reset();if(window.sxGeetest)window.sxGeetest.reset()}}})();</script>{{end}}` + authSubmitScript

const forgotThemeBody = `{{if .PasswordResetEnabled}}<div class="auth-wrap"><form class="auth" id="reset-form" method="post" action="/suxinvideo/forgot"><h2>找回密码</h2><div class="fi"><label>注册邮箱</label><input class="sx-input" name="email" type="email" required></div>{{.CaptchaWidget}}<div class="fi"><button id="reset-code" class="btn-line" type="button">发送重置码</button></div><div class="fi"><label>邮箱重置码</label><input class="sx-input" name="code" required></div><div class="fi"><label>新密码</label><input class="sx-input" name="password" type="password" minlength="6" required></div><div class="fi"><label>确认密码</label><input class="sx-input" name="repassword" type="password" minlength="6" required></div><button class="btn-main">重置密码</button><a class="btn-line" href="/suxinvideo/login">返回登录</a><p id="reset-result" role="status"></p></form></div><script>(function(){const form=document.getElementById('reset-form'),button=document.getElementById('reset-code'),output=document.getElementById('reset-result');if(!form||!button||!output)return;button.onclick=async()=>{button.disabled=true;const data=new FormData();data.set('email',form.elements.email.value);data.set('purpose','reset');['captcha','cf-turnstile-response','lot_number','captcha_output','pass_token','gen_time'].forEach(k=>{if(form.elements[k])data.set(k,form.elements[k].value)});try{const response=await fetch('/suxinvideo/sendcode',{method:'POST',body:data,credentials:'same-origin'}),text=await response.text();let result;try{result=JSON.parse(text)}catch(e){throw Error(text.slice(0,160))}if(!response.ok)throw Error(result.message||result.msg||'发送失败');output.textContent='重置码已发送'}catch(e){output.textContent=e.message}finally{button.disabled=false;const img=document.getElementById('sx-captcha-img');if(img)img.src='/suxinvideo/captcha?t='+Date.now();if(window.turnstile)window.turnstile.reset();if(window.sxGeetest)window.sxGeetest.reset()}}})();</script>{{else}}<div class="auth-wrap"><section class="auth" aria-labelledby="reset-unavailable"><h2 id="reset-unavailable">找回密码</h2><p role="status">本站暂未开启邮箱找回密码功能，请联系管理员重置密码。</p><a class="btn-line" href="/suxinvideo/login">返回登录</a></section></div>{{end}}` + authSubmitScript

// Account styles stay inside the account body: catalogue, live and player
// layouts keep their own theme rules. Suxinlite retains its PHP profile card
// and tabs; Iqiyi and SuxinPro retain their desktop side navigation.
const accountPageStyle = `<style>
.cms-body .sx-account-page{--account-accent:var(--pri,var(--red,var(--accent,#e5322d)));--account-surface:var(--bg2,var(--card,var(--surface,#1c2028)));--account-text:var(--txt,var(--text,#e9edf4));--account-muted:var(--sub,var(--muted,#969eac));margin:96px auto 32px;color:var(--account-text);min-width:0;max-width:100%}
.sx-theme-suxinlite .cms-body .sx-account-page{margin-top:28px}.sx-theme-guoguo .cms-body .sx-account-page{margin:0 auto 32px}
.cms-body .sx-account-page *{box-sizing:border-box}.cms-body .sx-account-page .sx-account-layout{margin:0;grid-template-columns:230px minmax(0,1fr);align-items:start}
.cms-body .sx-account-page .uc-side,.cms-body .sx-account-page .sx-account-content{min-width:0;max-width:100%;padding:24px;background:var(--account-surface)}
.cms-body .sx-account-page .sx-account-content{margin:0;min-height:400px;overflow-wrap:anywhere;text-align:left}
.cms-body .sx-account-page h2,.cms-body .sx-account-page h3{color:var(--account-text);font-size:20px;line-height:1.5;margin:0 0 18px}
.cms-body .sx-account-page .me{min-width:0}.cms-body .sx-account-page .av{flex:none}.cms-body .sx-account-page .me>div:last-child{min-width:0;overflow-wrap:anywhere}
.cms-body .sx-account-page .me b,.cms-body .sx-account-page .me span{display:block}.cms-body .sx-account-page .me span{margin-top:4px;font-size:12px;line-height:1.6;color:var(--account-muted)}
.cms-body .sx-account-page .me span,.cms-body .sx-account-page .uc-em{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow:hidden;line-height:1.6;max-height:3.2em}
.cms-body .sx-account-page .av img,.cms-body .sx-account-page .uc-av img{width:100%;height:100%;object-fit:contain;border-radius:50%}
.cms-body .sx-account-page .sx-account-nav{min-width:0}.cms-body .sx-account-page .sx-account-nav a,.cms-body .sx-account-page .sx-account-nav button{font:inherit;font-size:14px;line-height:1.5;text-decoration:none;cursor:pointer}
.cms-body .sx-account-page .uc-menu a,.cms-body .sx-account-page .uc-menu button{display:block;width:100%;text-align:left;padding:11px 12px;border:0;border-radius:8px;background:transparent;color:var(--account-muted)}
.cms-body .sx-account-page .uc-menu a:hover,.cms-body .sx-account-page .uc-menu a.on{background:var(--card,var(--surface-2,#252a33));color:var(--account-accent);font-weight:600}
.cms-body .sx-account-page .sx-account-logout{margin:0}.cms-body .sx-account-page .sx-account-logout button{color:#e85d5b}
.cms-body .sx-account-page .uc-head{margin-bottom:20px;min-width:0}.cms-body .sx-account-page .uc-head>.sx-account-identity{min-width:0;flex:1;overflow-wrap:anywhere}.cms-body .sx-account-page .uc-av{flex:none}
.cms-body .sx-account-page .uc-badges{margin-left:auto;flex:none}.cms-body .sx-account-page .uc-head .uc-badge{min-width:90px}.cms-body .sx-account-page .uc-tabs{align-items:center;gap:8px;margin:0 0 20px}
.cms-body .sx-account-page .uc-tabs a,.cms-body .sx-account-page .uc-tabs button{display:block;white-space:nowrap;padding:9px 18px;border:1px solid var(--line);border-radius:22px;background:var(--card);color:var(--account-muted)}
.cms-body .sx-account-page .uc-tabs a.on{background:var(--pri-grad);color:white;border-color:transparent}.cms-body .sx-account-page .uc-tabs .sx-account-logout button{color:#e85d5b}
.cms-body .sx-account-page .sx-account-actions{display:flex;align-items:flex-start;gap:12px;flex-wrap:wrap;margin-bottom:16px}.cms-body .sx-account-page .sx-account-actions form{margin:0}
.cms-body .sx-account-page .btn-main,.cms-body .sx-account-page .btn-line{display:inline-flex;align-items:center;justify-content:center;width:auto;max-width:100%;min-height:42px;padding:10px 20px;margin:0;border-radius:8px;font:inherit;font-size:14px;line-height:1.5;text-decoration:none;text-align:center;cursor:pointer}
.cms-body .sx-account-page .btn-line{border:1px solid var(--line);background:transparent;color:var(--account-text)}.cms-body .sx-account-page .sx-account-vip-action{background:var(--gold,#d4a84d);color:#241b08;box-shadow:none}
.cms-body .sx-account-page .sx-account-help{font-size:13px;line-height:1.8;color:var(--account-muted);margin:0 0 8px}.cms-body .sx-account-page .sx-account-section{padding-top:24px;margin-top:24px;border-top:1px solid var(--line)}
.cms-body .sx-account-page .sx-account-form{display:block;max-width:520px;min-width:0;margin:0}.cms-body .sx-account-page .sx-account-field{display:block;margin-bottom:16px}
.cms-body .sx-account-page .sx-account-field>span{display:block;font-size:13px;color:var(--account-muted);margin-bottom:7px}.cms-body .sx-account-page .sx-input{display:block;width:100%;min-width:0;max-width:100%;min-height:44px;font:inherit;font-size:14px}
.cms-body .sx-account-page .sx-account-result{margin:10px 0 0;font-size:13px;color:#ef7773;line-height:1.7;overflow-wrap:anywhere}.cms-body .sx-account-page button:disabled{cursor:default;opacity:.55}
.cms-body .sx-account-page a:focus-visible,.cms-body .sx-account-page button:focus-visible{outline:2px solid var(--account-accent);outline-offset:3px}
.cms-body .sx-account-page .sx-page-heading{margin:0 0 18px;gap:12px;flex-wrap:wrap}.cms-body .sx-account-page .sx-page-heading h2{margin:0}
.cms-body .sx-account-page .hist-grid,.cms-body .sx-account-page .kgrid,.cms-body .sx-account-page .grid,.cms-body .sx-account-page .iqgrid{display:grid;columns:auto;grid-template-columns:repeat(auto-fill,minmax(145px,1fr));gap:16px;margin:0}
.cms-body .sx-account-page .hist-card,.cms-body .sx-account-page .kcard,.cms-body .sx-account-page .vcard,.cms-body .sx-account-page .iqc{min-width:0;max-width:100%;margin:0;display:block}
.cms-body .sx-account-page .hnm{display:block;margin-top:8px;color:var(--account-text);font-size:14px;line-height:1.6;overflow-wrap:anywhere}.cms-body .sx-account-page .hmeta{color:var(--account-muted);font-size:12px;line-height:1.7}
.cms-body .sx-account-page .sx-empty{grid-column:1/-1;padding:50px 12px;margin:0;color:var(--account-muted);font-size:14px;line-height:1.8;text-align:center}
.cms-body .sx-account-page .sx-account-orders{min-width:0}.cms-body .sx-account-page .ut{width:100%;table-layout:fixed;border-collapse:collapse}
.cms-body .sx-account-page .ut td,.cms-body .sx-account-page .ut th{padding:12px 10px;overflow-wrap:anywhere;vertical-align:top;font-size:13px;text-align:left;line-height:1.7;border-bottom:1px solid var(--line)}
.cms-body .sx-account-page .ut th{color:var(--account-muted)}.cms-body .sx-account-page .ut td a{color:var(--account-accent)}.cms-body .sx-account-page .ut th:first-child{width:23%}.cms-body .sx-account-page .ut th:nth-child(2){width:23%}
.cms-body .sx-account-page .sx-order-paid{color:var(--green,#41bc86)}.cms-body .sx-account-page .sx-order-pending{color:var(--gold,#dfb45c)}
.cms-body .sx-account-page .paycards{grid-template-columns:repeat(auto-fill,minmax(min(175px,100%),1fr));gap:14px;margin:0 0 28px}.cms-body .sx-account-page .paycard{min-width:0;max-width:100%;padding:18px;text-align:left}
.cms-body .sx-account-page .paycard span{display:block;overflow-wrap:anywhere}.cms-body .sx-account-page .paycard.on,.cms-body .sx-account-page .paymethods .pm.on{border-color:var(--account-accent)}
.cms-body .sx-account-page .paymethods{display:flex;gap:10px;flex-wrap:wrap;margin:0 0 22px}.cms-body .sx-account-page .paymethods .pm{min-height:42px;padding:10px 16px;border:1px solid var(--line);border-radius:8px;background:var(--card,var(--surface-2,#252a33));color:var(--account-text);font:inherit;font-size:14px;cursor:pointer}
.cms-body .sx-account-page .sx-cashier,.cms-body .sx-account-page .sx-pay-result{max-width:none;text-align:center}.cms-body .sx-account-page .qrbox{max-width:100%;overflow-wrap:anywhere}.cms-body .sx-account-page .qrbox img{width:220px;max-width:100%;height:auto}
.cms-body .sx-account-page .sx-pay-result>p,.cms-body .sx-account-page .sx-cashier>p{margin-bottom:14px;font-size:14px;line-height:1.8}.cms-body .sx-account-page .sx-account-result-actions{display:flex;gap:12px;flex-wrap:wrap;justify-content:center;margin-top:22px}
@media(max-width:900px){.cms-body .sx-account-page{margin-top:84px}.sx-theme-suxinlite .cms-body .sx-account-page{margin-top:22px}.cms-body .sx-account-page .sx-account-layout{grid-template-columns:minmax(0,1fr);gap:18px}.cms-body .sx-account-page .uc-side{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px;padding:18px}.cms-body .sx-account-page .uc-side .me,.cms-body .sx-account-page .uc-side .sx-account-nav{grid-column:1/-1}.cms-body .sx-account-page .uc-side .me{margin:0}.cms-body .sx-account-page .uc-side .vip{display:block;margin:0;padding:10px 12px;min-width:0;font-size:12px}.cms-body .sx-account-page .uc-side .vip b{display:block;margin-top:4px}.cms-body .sx-account-page .uc-menu{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px;margin:0}.cms-body .sx-account-page .uc-menu a,.cms-body .sx-account-page .uc-menu button{padding:10px 4px;text-align:center;font-size:13px;margin:0}.cms-body .sx-account-page .uc-head{padding:24px}.cms-body .sx-account-page .uc-badges{width:100%;margin-left:0;gap:10px}.cms-body .sx-account-page .uc-head .uc-badge{flex:1}}
@media(max-width:550px){.cms-body .sx-account-page .uc-side,.cms-body .sx-account-page .sx-account-content{padding:16px}.cms-body .sx-account-page .sx-account-content{min-height:280px}.cms-body .sx-account-page .uc-head{padding:20px;gap:14px}.cms-body .sx-account-page .uc-av{width:48px;height:48px}.cms-body .sx-account-page .uc-nm{font-size:18px}.cms-body .sx-account-page .uc-tabs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin-bottom:16px}.cms-body .sx-account-page .uc-tabs a,.cms-body .sx-account-page .uc-tabs button{width:100%;padding:9px 4px;text-align:center;font-size:12px}.cms-body .sx-account-page .sx-account-actions{display:grid;grid-template-columns:minmax(0,1fr);gap:10px}.cms-body .sx-account-page .sx-account-actions .btn-main{width:100%}.cms-body .sx-account-page h2,.cms-body .sx-account-page h3{font-size:18px}.cms-body .sx-account-page .hist-grid,.cms-body .sx-account-page .kgrid,.cms-body .sx-account-page .grid,.cms-body .sx-account-page .iqgrid{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.cms-body .sx-account-page .sx-account-form>.btn-main{width:100%}.cms-body .sx-account-page .ut thead{display:none}.cms-body .sx-account-page .ut tbody{display:grid;gap:12px}.cms-body .sx-account-page .ut tr{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:14px;background:var(--card,var(--surface-2,#252a33));border:1px solid var(--line);border-radius:10px}.cms-body .sx-account-page .ut td{display:block;padding:0;border:0;font-size:13px;min-width:0}.cms-body .sx-account-page .ut td:first-child,.cms-body .sx-account-page .ut td:nth-child(2),.cms-body .sx-account-page .ut td[colspan]{grid-column:1/-1}.cms-body .sx-account-page .ut td[data-label]:before{content:attr(data-label);display:block;margin-bottom:3px;color:var(--account-muted);font-size:11px}.cms-body .sx-account-page .ut td[colspan]{text-align:center;padding:16px 0}.cms-body .sx-account-page .paycards{grid-template-columns:minmax(0,1fr)}.cms-body .sx-account-page .paymethods .pm{flex:1;min-width:110px;text-align:center}}
</style>`

const accountNavigation = `<a href="/suxinvideo/center">我的账户</a><a href="/suxinvideo/history">观看历史</a><a href="/suxinvideo/favorites">我的收藏</a><a href="/suxinvideo/orders">充值订单</a><a href="/suxinvideo/pay">充值中心</a><form class="sx-account-logout" method="post" action="/suxinvideo/logout"><button type="submit">退出登录</button></form>`

const accountProfileImage = `<img src="{{if .User.avatar}}{{.User.avatar}}{{else}}` + defaultLogoURL + `{{end}}" alt="用户头像" width="52" height="52" onerror="this.onerror=null;this.src='` + defaultLogoURL + `'">`

const accountPageScript = `<script>(function(){
 document.querySelectorAll('[data-account-time]').forEach(node=>{const value=node.dataset.accountTime;if(/^\d{10,13}$/.test(value)){const date=new Date(Number(value)*(value.length===10?1000:1));if(!Number.isNaN(date.getTime()))node.textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(date)}});
 document.querySelectorAll('form[data-account-submit]').forEach(form=>form.addEventListener('submit',async event=>{
  event.preventDefault();const button=form.querySelector('button[type="submit"]'),output=form.querySelector('.sx-account-result');button.disabled=true;output.textContent='正在提交…';
  try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),credentials:'same-origin'});if(response.redirected){location.assign(response.url);return}const raw=(await response.text()).trim();if(!response.ok)throw Error(raw.slice(0,180)||'提交失败，请稍后重试');let result;try{result=JSON.parse(raw)}catch(error){throw Error('服务器返回异常，请稍后重试')}if(result.code!==0&&result.code!==1)throw Error(result.message||result.msg||'提交失败');location.assign(result.data?.redirect||'/suxinvideo/center')}
  catch(error){output.textContent=error.message||'网络异常，请稍后重试'}finally{button.disabled=false}
 }));
})();</script>`

func accountPageData(user row, extra map[string]any) map[string]any {
	remaining := gconv.Int64(user["vip_expire"]) - time.Now().Unix()
	data := map[string]any{"User": user, "IsVIP": remaining > 0, "VIPDays": (remaining + 86399) / 86400}
	for key, value := range extra {
		data[key] = value
	}
	return data
}

func accountPageBody(active, content string) string {
	nav := strings.Replace(accountNavigation, `href="/suxinvideo/`+active+`"`, `class="on" aria-current="page" href="/suxinvideo/`+active+`"`, 1)
	return accountPageStyle + `<section class="sx-account-page" aria-label="个人中心">{{if eq .Theme "suxinlite"}}<header class="uc-head"><div class="uc-av">` + accountProfileImage + `</div><div class="sx-account-identity"><div class="uc-nm">{{.User.name}}</div><div class="uc-em" title="{{.User.email}}">{{.User.email}}</div></div><div class="uc-badges"><div class="uc-badge"><b>{{if .IsVIP}}VIP · {{.VIPDays}} 天{{else}}未开通{{end}}</b><span>会员状态</span></div><div class="uc-badge"><b>{{.User.points}}</b><span>积分余额</span></div></div></header><nav class="uc-tabs sx-account-nav" aria-label="个人中心菜单">` + nav + `</nav>{{else}}<div class="uc sx-account-layout"><aside class="uc-side"><div class="me"><div class="av">` + accountProfileImage + `</div><div><b>{{.User.name}}</b><span title="{{.User.email}}">{{.User.email}}</span></div></div><div class="vip"><div>会员状态</div><b>{{if .IsVIP}}VIP · {{.VIPDays}} 天{{else}}未开通{{end}}</b></div><div class="vip"><div>积分余额</div><b>{{.User.points}}</b></div><nav class="uc-menu sx-account-nav" aria-label="个人中心菜单">` + nav + `</nav></aside>{{end}}<div class="uc-main sx-account-content">` + content + `</div>{{if ne .Theme "suxinlite"}}</div>{{end}}</section>` + accountPageScript
}

var centerThemeBody = accountPageBody("center", `<h2>我的账户</h2><div class="sx-account-actions"><form method="post" action="/suxinvideo/sign" data-account-submit><button type="submit" class="btn-main">每日签到 +{{.SignPoints}} 积分</button><p class="sx-account-result" role="status"></p></form><a class="btn-main sx-account-vip-action" href="/suxinvideo/pay">开通或续费 VIP</a></div><p class="sx-account-help">签到可获得积分，用于解锁单片；VIP 有效期内可观看会员影片。</p><section class="sx-account-section"><h3>修改昵称</h3><form class="sx-account-form" method="post" action="/suxinvideo/account" data-account-submit><input type="hidden" name="act" value="nickname"><label class="sx-account-field"><span>昵称</span><input class="sx-input" name="name" minlength="2" maxlength="20" value="{{.User.name}}" required autocomplete="nickname" placeholder="2–20 个字符"></label><button type="submit" class="btn-main">保存昵称</button><p class="sx-account-result" role="status"></p></form></section><section class="sx-account-section"><h3>修改密码</h3><form class="sx-account-form" method="post" action="/suxinvideo/account" data-account-submit><input type="hidden" name="act" value="password"><label class="sx-account-field"><span>当前密码</span><input class="sx-input" name="oldpwd" type="password" required autocomplete="current-password"></label><label class="sx-account-field"><span>新密码</span><input class="sx-input" name="newpwd" type="password" minlength="6" maxlength="72" required autocomplete="new-password" placeholder="至少 6 个字符"></label><label class="sx-account-field"><span>确认新密码</span><input class="sx-input" name="repwd" type="password" minlength="6" maxlength="72" required autocomplete="new-password" placeholder="再次输入新密码"></label><button type="submit" class="btn-main">修改密码</button><p class="sx-account-result" role="status"></p></form></section>`)

var historyThemeBody = accountPageBody("history", `<div class="sx-page-heading"><h2>观看历史</h2>{{if .Records}}<form method="post" action="/suxinvideo/history/clear"><button type="submit" class="btn-line" onclick="return confirm('确定清空全部观看历史？')">清空历史</button></form>{{end}}</div><div class="hist-grid">{{range .Records}}<div class="hist-card"><a class="hp" href="/suxinvideo/play?id={{.id}}&episode={{.episode_index}}"><img src="{{pic .pic}}" loading="lazy" alt="{{.name}}"><span class="rm">看到第 {{.episode}} 集</span><div class="prog"><i style="width:100%"></i></div></a><a class="hnm" href="/suxinvideo/detail?id={{.id}}">{{.name}}</a><div class="hmeta">看到第 {{.episode}} 集</div></div>{{else}}<p class="sx-empty">暂无观看记录，去看几部影片吧</p>{{end}}</div>`)

var favoritesThemeBody = accountPageBody("favorites", `<div class="sx-page-heading"><h2>我的收藏</h2></div>{{template "cards" .Vods}}`)

var ordersThemeBody = accountPageBody("orders", `<h2>充值订单</h2><div class="sx-account-orders"><table class="ut"><thead><tr><th scope="col">订单号</th><th scope="col">套餐</th><th scope="col">金额</th><th scope="col">方式</th><th scope="col">状态</th><th scope="col">时间</th></tr></thead><tbody>{{range .Orders}}<tr><td data-label="订单号"><a href="/suxinvideo/pay/result?ono={{.order_no}}">{{.order_no}}</a></td><td data-label="套餐">{{.title}}</td><td data-label="金额">¥{{.amount}}</td><td data-label="方式">{{.pay_type}}</td><td data-label="状态">{{if eq (str .status) "1"}}<span class="sx-order-paid">已支付</span>{{else if eq (str .status) "2"}}已取消{{else}}<span class="sx-order-pending">待支付</span>{{end}}</td><td data-label="时间"><time data-account-time="{{.created}}">{{.created}}</time></td></tr>{{else}}<tr><td colspan="6">暂无订单</td></tr>{{end}}</tbody></table></div>`)
