// =================================================================================
// This is auto-generated by Suxin CLI tool only once. Fill this file as you wish.
// =================================================================================

package common

import (
	"context"

	"github.com/suxinwl/GoSuxin/framework/net/ghttp"
)

var R = new(Router)

type Router struct{}

func (router *Router) BindController(ctx context.Context, group *ghttp.RouterGroup) {
	group.Group("/common", func(group *ghttp.RouterGroup) {
		//公共工具函数不需token验证
		group.Bind(
			NewBasetool(),
		)
	})
}
