// =================================================================================
// This is auto-generated by Suxin CLI tool only once. Fill this file as you wish.
// =================================================================================

package common

import (
	"github.com/suxinwl/GoSuxin/api/common"
)

type ControllerBasetool struct{}

func NewBasetool() common.ICommonBasetool {
	return &ControllerBasetool{}
}
