// =================================================================================
// This is auto-generated by Suxin CLI tool only once. Fill this file as you wish.
// =================================================================================

package user_ext

import (
	"github.com/suxinwl/GoSuxin/framework/cmd/suxin/internal/cmd/testdata/genctrl/multi/api/app/user/user_ext"
)

type ControllerV1 struct{}

func NewV1() user_ext.IUserExtV1 {
	return &ControllerV1{}
}
