<template><div class="card"><div class="tabs"><button v-for="section in sections" :key="section.id" :class="{on:tab===section.id}" @click="tab=section.id">{{ section.name }}</button></div><form @submit.prevent="save"><div class="form"><div v-for="field in activeFields" :key="field.key" class="fi"><label>{{ field.label }}</label><textarea v-if="field.long" v-model="values[field.key]" :placeholder="field.secret ? '留空则保留现有值' : ''" /><select v-else-if="field.options" v-model="values[field.key]"><option v-for="option in field.options" :key="option.value" :value="option.value">{{ option.label }}</option></select><input v-else v-model="values[field.key]" :type="field.secret ? 'password' : field.numeric ? 'number' : 'text'" :placeholder="field.secret ? '留空则保留现有值' : ''" /><div v-if="field.image" class="brand-setting"><img v-if="values[field.key]" :src="values[field.key]" :alt="field.label" class="brand-preview" /><input v-if="actions.saveConfig" type="file" accept="image/png,image/jpeg,image/webp" @change="uploadBrand(field.key,$event)" /><small>PNG / JPEG / WebP，最大 2 MB；上传后立即生效。也可填写 HTTPS 图片地址并保存。</small></div><small v-if="field.hint" class="hint">{{ field.hint }}</small></div></div><div v-if="tab==='smtp'" class="searchbar"><input v-model="testEmail" type="email" placeholder="发送测试邮件到" /><button v-if="actions.mailTest" class="btn plain" type="button" @click="mailTest">发送测试邮件</button></div><div v-if="tab==='safe'" class="form"><b>修改管理员密码</b><div class="fi"><label>旧密码</label><input v-model="password.oldpassword" type="password" /></div><div class="fi"><label>新密码（至少8位）</label><input v-model="password.password" type="password" /></div><div class="fi"><label>确认新密码</label><input v-model="password.repassword" type="password" /></div><button v-if="actions.adminPassword" class="btn blue" type="button" @click="changePassword">修改密码</button></div><button v-if="actions.saveConfig" class="btn" type="submit">保存全部设置</button></form></div></template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { Message } from '@arco-design/web-vue';
import { defHttp } from '@/utils/http';
type Field={key:string;label:string;long?:boolean;secret?:boolean;numeric?:boolean;image?:boolean;hint?:string;options?:{value:string;label:string}[]};
const f=(key:string,label:string,extra:Partial<Field>={}):Field=>({key,label,...extra});
const yes=[{value:'1',label:'开启'},{value:'0',label:'关闭'}];
const defaults:Record<string,string>={player_ad_filter:'1',player_ad_domains:'',yqk_navigation_enable:'1',home_recommend_source:'local',home_hero_source:'yqk',content_block_enable:'1',content_block_keywords:'擦边\n换妻\n情色\n色情\n成人视频\n成人影片\n三级电影\n三级片',content_block_categories:'伦理片\n情色\n色情\n成人影视\n三级电影'};
const sections=[
  {id:'content',name:'内容屏蔽',fields:[f('content_block_enable','启用内容屏蔽',{options:yes,hint:'对全部片源生效。新采集跳过命中影片，已采集影片从前台列表、搜索和播放中隐藏；保留原始数据。'}),f('content_block_keywords','标题关键词',{long:true,hint:'每行一个关键词，按标题包含匹配，不区分大小写。最多 200 条，每条最多 120 字；留空表示不按标题屏蔽。'}),f('content_block_categories','屏蔽类别',{long:true,hint:'每行一个类别词，匹配片源类别、影片标签以及本站分类和父分类。留空表示不按类别屏蔽。'})]},
  {id:'site',name:'站点信息',fields:[f('site_name','网站名称'),f('site_logo','网站 Logo',{image:true}),f('site_favicon','浏览器图标',{image:true}),f('user_default_avatar','用户默认头像',{image:true}),f('site_icp','备案号'),f('site_keywords','SEO关键词'),f('site_description','SEO描述',{long:true}),f('site_mode','影视站模式',{options:[{value:'cms',label:'CMS模式'},{value:'waterfall',label:'瀑布流模式'},{value:'movie',label:'电影模式'}]}),f('site_template','默认模板',{options:[]}),f('yqk_navigation_enable','小柒频道导航',{options:yes,hint:'首页导航使用短剧、奈飞、电影、电视剧、动漫、综艺、高清韩剧及体育频道；关闭后使用本站分类。'}),f('home_recommend_source','首页推荐内容',{options:[{value:'yqk',label:'小柒最近更新与热播'},{value:'local',label:'本站多片源影片（推荐）'}],hint:'本站多片源合并展示最近更新与热播；小柒远端推荐仍可单独选择。'}),f('home_hero_source','首页顶部轮播',{options:[{value:'yqk',label:'小柒热门影片'},{value:'managed',label:'幻灯管理'}],hint:'选择幻灯管理后优先显示后台启用的顶部幻灯。'}),f('source_discovery_enable','进入影片自动补源',{options:yes}),f('source_discovery_interval','补源检测间隔（分钟，15–1440）',{numeric:true}),f('yqk_bootstrap_url','小柒动态入口（JSON）',{hint:'填写小柒 APP 提供的 HTTPS 动态入口 JSON 地址；保存后采集与播放自动读取最新服务地址。采集管理只需一个 yqk://app 聚合接口。'})]},
  {id:'playback',name:'播放设置',fields:[f('player_parse','默认解析地址',{hint:'使用解析服务时，地址须包含 {url}；留空使用影片原有播放线路。'}),f('player_autoplay','视频自动播放',{options:yes}),f('player_ad_filter','过滤片源插播广告',{options:yes,hint:'仅过滤播放清单中明确标记的插播广告或下方指定广告域名的片段。画面内嵌字幕、水印和已压入视频的广告不能通过此开关消除。'}),f('player_ad_domains','广告片段域名',{long:true,hint:'每行一个广告域名，如 ads.example.com，匹配时包含其子域名；最多 64 条。只填域名，不填写完整 URL、IP 地址或通配符。留空仍过滤清单中明确标记的广告；请勿填写正常视频 CDN 域名。'})]},
  {id:'member',name:'会员/注册',fields:[f('member_enable','会员系统',{options:yes}),f('register_enable','注册功能',{options:yes}),f('comment_audit','评论审核',{options:yes}),f('comment_enable','评论功能',{options:yes}),f('points_sign','每日签到积分',{numeric:true}),f('points_register','注册赠送积分',{numeric:true}),f('points_pay_rate','充值比例',{numeric:true}),f('img_auto_clean_enable','每日清理未引用图片',{options:yes}),f('kp_icon_search','SuxinPro 搜索图标',{options:yes}),f('kp_icon_history','SuxinPro 历史图标',{options:yes}),f('kp_icon_user','SuxinPro 头像图标',{options:yes}),f('kp_slide_enable','SuxinPro 大图幻灯',{options:yes}),f('kp_slide_count','幻灯数量',{numeric:true}),f('kp_slide_source','幻灯数据源',{options:[{value:'new',label:'最新影片'},{value:'hot',label:'最热影片'},{value:'slide',label:'幻灯管理'}]}),f('rewrite_enable','伪静态 URL',{options:yes}),f('browser_check_enable','QQ/微信浏览器拦截',{options:yes}),f('home_slide_enable','首页幻灯片',{options:yes})]},
  {id:'verify',name:'验证码',fields:[f('captcha_provider','验证方式',{options:[{value:'graph',label:'图形验证码'},{value:'geetest',label:'极验 v4'},{value:'turnstile',label:'Cloudflare Turnstile'}]}),f('geetest_id','极验 captcha_id'),f('geetest_key','极验 captcha_key',{secret:true}),f('turnstile_site_key','Turnstile Site Key'),f('turnstile_secret','Turnstile Secret Key',{secret:true})]},
  {id:'smtp',name:'邮件服务',fields:[f('smtp_host','SMTP 服务器'),f('smtp_port','端口',{numeric:true}),f('smtp_secure','加密方式',{options:[{value:'ssl',label:'SSL'},{value:'tls',label:'TLS'},{value:'none',label:'无'}]}),f('smtp_user','发件账号'),f('smtp_pass','密码/授权码',{secret:true}),f('smtp_from_name','发件人显示名')]},
  {id:'pay',name:'支付设置',fields:[f('codepay_gateway','码支付网关'),f('codepay_pid','码支付商户PID'),f('codepay_key','码支付密钥',{secret:true}),f('codepay_channel','码支付默认通道'),f('epay_gateway','易支付网关'),f('epay_pid','易支付商户PID'),f('epay_key','易支付密钥',{secret:true}),f('epay_channel','易支付默认通道'),f('usdt_address','TRC20收款地址'),f('usdt_rate','USDT汇率'),f('usdt_trongrid_key','TronGrid API Key',{secret:true}),f('wxpay_appid','微信 APPID'),f('wxpay_mchid','微信商户号'),f('wxpay_key','微信 API 密钥',{secret:true}),f('alipay_appid','支付宝 APPID'),f('alipay_private_key','支付宝应用私钥',{long:true,secret:true}),f('alipay_public_key','支付宝公钥',{long:true})]},
  {id:'cdn',name:'CDN加速',fields:[f('cdn_mode','Cloudflare CDN 模式',{options:yes})]},
  {id:'ad',name:'广告设置',fields:['home','playtop','playbottom','footer'].flatMap(slot=>[f(`ad_${slot}_enable`,`${slot} 广告位`,{options:yes}),f(`ad_${slot}_code`,`${slot} 广告代码`,{long:true})])},
  {id:'safe',name:'安全',fields:[f('debug','调试模式',{options:yes}),f('admin_remark','后台备注'),f('search_limit_enable','搜索频率限制',{options:yes}),f('search_limit_times','窗口内最大次数',{numeric:true}),f('search_limit_window','时间窗口（秒）',{numeric:true}),f('baidu_push_site','百度推送站点'),f('baidu_push_token','百度推送 token',{secret:true})]},
];
defineProps<{actions:Record<string,boolean>}>();
const tab=ref('site');const values=reactive<Record<string,string>>({});const testEmail=ref('');const password=reactive({oldpassword:'',password:'',repassword:''});
const activeFields=computed(()=>sections.find(section=>section.id===tab.value)?.fields||[]);
async function load(){const config=await defHttp.get({url:'/suxinvideo/config'});const themeField=sections.find(section=>section.id==='site')?.fields.find(field=>field.key==='site_template');if(themeField)themeField.options=(config.__themes||[]).map((item:any)=>({value:item.code,label:item.name}));for(const section of sections)for(const field of section.fields)values[field.key]=field.secret?'':String(config[field.key]??defaults[field.key]??'');}
async function save(){const changes:Record<string,string>={};for(const field of activeFields.value){const value=values[field.key]||'';if(!field.secret||value)changes[field.key]=value;}await defHttp.post({url:'/suxinvideo/saveConfig',params:{values:changes}});Message.success('设置已保存');}
async function uploadBrand(key:string,event:Event){
  const input=event.target as HTMLInputElement;
  const file=input.files?.[0];
  if(!file)return;
  try{
    const result:any=await defHttp.uploadFile({url:'/admin/suxinvideo/saveConfig'},{name:'file',file,filename:file.name,data:{kind:key}});
    if(result.code!==0||!result.data?.url)throw Error(result.message||'\u4e0a\u4f20\u5931\u8d25');
    values[key]=result.data.url;
    Message.success('\u56fe\u6807\u5df2\u66f4\u65b0');
  }catch(error:any){Message.error(error.message||'\u4e0a\u4f20\u5931\u8d25');}
  finally{input.value='';}
}
async function mailTest(){await defHttp.post({url:'/suxinvideo/mailTest',params:{email:testEmail.value}});Message.success('测试邮件已发送');}
async function changePassword(){if(password.password!==password.repassword||password.password.length<8){Message.error('新密码至少8位且两次输入一致');return;}await defHttp.post({url:'/suxinvideo/adminPassword',params:password});Message.success('密码已修改，请重新登录');}
onMounted(load);
</script>

<style scoped>
.brand-setting{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-top:8px}.brand-preview{width:48px;height:48px;object-fit:contain;background:#f2f3f5;border-radius:6px;padding:4px}.brand-setting small{color:#86909c}.brand-setting input[type=file]{max-width:240px}
</style>
