<template><div class="card"><div class="tabs"><button class="on">模板</button></div><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:14px"><div v-for="item in themes" :key="item.code" style="border:1px solid var(--line);border-radius:10px;overflow:hidden"><div style="height:120px;background:linear-gradient(135deg,#232733,#3a4152);display:flex;align-items:center;justify-content:center;color:#fff;font-weight:700;font-size:18px">{{ item.name }}</div><div style="padding:14px"><div style="display:flex;justify-content:space-between"><b>{{ item.name }}</b><span class="tag b">v{{ item.version || '1.0' }}</span></div><p class="hint">{{ item.description || item.code }}</p><button v-if="actions.saveConfig" class="btn sm" :disabled="active===item.code" @click="enable(item.code)">{{ active===item.code ? '使用中' : '启用模板' }}</button> <button v-if="actions.uninstallTheme && !builtins.includes(item.code)" class="btn plain sm" @click="uninstall(item.code)">卸载</button></div></div><p v-if="!themes.length" class="hint">暂无本地模板</p></div><div v-if="actions.installTheme" style="margin-top:18px;border-top:1px solid var(--line);padding-top:14px"><b>本地上传安装</b><p class="hint">安装包根目录需包含 manifest.json 和 static/css/main.css</p><input ref="input" type="file" accept=".zip" @change="upload" /></div></div></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { Message, Modal } from '@arco-design/web-vue';
import { defHttp } from '@/utils/http';
defineProps<{permissions:Record<string,boolean>;actions:Record<string,boolean>}>();
const themes=ref<Record<string,any>[]>([]);const active=ref('');const builtins=['suxinlite','suxinpro','iqiyi','guoguo'];const input=ref<HTMLInputElement>();
async function load(){const [list,config]=await Promise.all([defHttp.get({url:'/suxinvideo/list',params:{table:'plugin',page:1}}),defHttp.get({url:'/suxinvideo/config'})]);themes.value=(list.list||[]).filter((item:any)=>item.type==='template');active.value=config.site_template||'suxinlite';}
async function enable(code:string){await defHttp.post({url:'/suxinvideo/saveConfig',params:{values:{site_template:code}}});Message.success('已启用');await load();}
function uninstall(code:string){Modal.confirm({title:'确认卸载模板？',content:'将卸载此模板，当前使用中的模板需先切换。',onOk:async()=>{await defHttp.post({url:'/suxinvideo/uninstallTheme',params:{code}});await load();}});}
async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;try{const result=await defHttp.uploadFile({url:'/admin/suxinvideo/installTheme'},{name:'file',file,filename:file.name,data:{}});if(result.code!==0)throw Error(result.message||'安装失败');Message.success('模板已安装');await load();}catch(error:any){Message.error(error.message||'安装失败');}finally{if(input.value)input.value.value='';}}
onMounted(load);
</script>
