// =================================================================================
// This is auto-generated by Suxin CLI tool only once. Fill this file as you wish.
// =================================================================================

package wxapp

import (
	"github.com/suxinwl/GoSuxin/api/wxapp"
)

type ControllerV1 struct{}

func NewV1() wxapp.IWxappV1 {
	return &ControllerV1{}
}
