// =================================================================================
// This is auto-generated by Suxin CLI tool only once. Fill this file as you wish.
// =================================================================================

package wxapp

import (
	"context"

	"github.com/suxinwl/GoSuxin/framework/net/ghttp"
)

var R = new(Router)

type Router struct{}

func (router *Router) BindController(ctx context.Context, group *ghttp.RouterGroup) {
	group.Group("/wxapp", func(group *ghttp.RouterGroup) {
		//登录验证拦截
		// group.Middleware(middleware.Token)
		//引入接口路由
		group.Bind(
			NewV1(),
		)
	})
}
